### ISSUE TITLE
Insert of multiple documents with errors

### ISSUE THREAD

**Issue by tib** [OpenKitten/MongoKitten#101]
The insert method won't return any object ids, if a duplicate key error happens, but it throws an error. 

This behaviour would be acceptable if the stoppingOnError parameter is true, but this parameter suggests that if the insertion contains a "bad object", the work continues, and the result outcome should be the array of the inserted identifiers. 

```swift
do {
    let identifiers = try collection.insert(documents, stoppingOnError: false)
}
catch {
    //this is gona be called... :(
    print(error) 
}
```

Is is possible to get back the inserted identifiers after the error happens?

The ideal solution would be to alternate the insert function behaviour, and check the stoppingOnError property & handle the outcome according to it. Does this make any sense or am I missing something?

**Comment by Joannis** [comment]
Thanks for the issue. I've been thinking about this for a bit now, but I don't think it's easy to solve. I can, however, modify the error signature to contain the inserted ids. Would that help?

In this case you could do something similar to this:

```swift
do {
    let identifiers = try collection.insert(documents, stoppingOnError: false)
}
catch  {
    if case .insertFailure(let insertedIds) = error {
        // handle inserted Ids
    } else {
        print(error)
    }
}
```

**Comment by tib** [comment]
First of all, thank you for the quick reply, with the proposed solution users could be able to check the inserted identifiers, but know nothing about the failed ones. I think we should separate the objects into two categories: succesful insert identifiers, and failed objects (with the reason of the failure maybe).

```swift

do {
    let identifiers = try collection.insert(documents, stoppingOnError: false)
}
catch  {
    if case .insertFailure(let insertedIds, let failedObjects) = error {
        // handle inserted Ids or failed objects if needed
    } else {
        print(error)
    }
}

```

What do you think? Could we do something like this? It would be a big help for my current project. :)

**Comment by Joannis** [comment]
Sounds good. I'm thinking of making it a bit different even. `struct InsertFailure` which has helper methods, too, to get information about the successful and failed documents. I'll be working on this later this weekend.

**Comment by tib** [comment]
Thank you! I can't wait to see the final results. ;)

**Comment by Joannis** [comment]
I've worked on it and tested it in MongoKitten 4. I'll be backporting this now.

**Comment by Joannis** [comment]
https://github.com/OpenKitten/MongoKitten/blob/bson5/Tests/MongoKittenTests/CollectionTests.swift#L601

Here is the test, do you think this is enough?

**Comment by tib** [comment]
Cool, I like this solution. Clean & simple enough! ;)

**Comment by Joannis** [comment]
Looks like I'm ready. It's passing the tests but I cannot tag it a 3.1.7. It's now 3.2.0.
If you don't mind, please post some feedback on the available variables and if you miss anything in the errors like helper functions/variables, please let me know. If everything's fine you can close the issue.

**Comment by tib** [comment]
Thank you, I'll have some tests later on today if everything works, I'll close the issue. 👍

**Comment by tib** [comment]
Strange error happened after the swift build command:

```
/home/tib/linux/Balaton/Packages/MongoKitten-3.2.0/Sources/MongoKitten/Collection/Collection.swift:161:29: error: value of type 'UnsafePointer<Any>' has no member 'reversed'
            for position in positions.reversed() {
                            ^~~~~~~~~ ~~~~~~~~
<unknown>:0: error: build had 1 command failures
```
I am using:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

$ swift --version
Swift version 3.0.2 (swift-3.0.2-RELEASE)
```

Is it possible that something went wrong with the update?

**Comment by Joannis** [comment]
I'm getting this in the CLI but not Xcode. Let me look into this. Thanks for the heads up

**Comment by Joannis** [comment]
Swift 3.0.2-RELEASE has some random troubles inferring the type at that line of code. I fixed it in 3.2.1

**Comment by tib** [comment]
Now it compiles, but I have a unique index on my collection:

```swift
try collection.createIndex(named: "unique-ab", withParameters: .unique, .compound(fields: [
                ("a", Int32(1)),
                ("b", Int32(1)),
            ]))
```

... and I am trying to insert duplicate items:

```swift
do {
        let identifiers = try collection.insert(documents, stoppingOnError: false)
        print("without error") 
        print(identifiers)
}
catch let insertErrors as InsertErrors {
    print("with error")
    print(insertErrors.successfulIds)
    print(insertErrors.errors)
}
catch {
    print("error")
}
```

The code never gets to the first catch block, but it should. I've got all the inserted identifiers inside the "without error" block, but I'm 100% sure that I have dupes, because if I change the stoppingOnError property, it'll go directly to the catch block.

**Comment by Joannis** [comment]
This is MongoDB behaviour, primarily. StoppingOnError is false by default, and on false it will continue to insert after duplicates. I cannot throw an error because that would abort the insert operation halfway through. Any idea what the preferred approach should be?

**Comment by tib** [comment]
What if you check the BulkWriteResult in the end, and if it contains .writeErrors, you throw an exception, regardless of the result. That exception could contain all the necessary info like now. 

My main problem with the current solution is that I can not get the duplicate errors... because that catch block is never called, but it should, because the insert operation had errors. Hiding the problem is not really a practical solution in my opinion. 

Maybe I could help with the fix, I'll have some time later tonight.

**Comment by Joannis** [comment]
I guess that's probably the best way. 👍

**Comment by Joannis** [comment]
It's going to be tagged 3.2.2 after travis marks the last commit as succeeding.

**Comment by tib** [comment]
I'll test it, I just wanted to look after this issue. ;)

**Comment by Joannis** [comment]
Tagged

**Comment by tib** [comment]
Yaaaay, it's perfect! Works like magic! Thank you for the "fix"! 🥇 🎊 👍
