### ISSUE TITLE
Log level can't be set

### ISSUE THREAD

**Issue by tib** [OpenKitten/MongoKitten#102]
The log level can not be set, and the logger output can't be disabled.

```bash
18:39:33 [Info] Authenticating the connection to MongoKitten.Database<mongodb://localhost:27017/kittens>    [Main:Convenience.swift:info] org.openkitten.mongokitten
```

This could be really proplematic for linux shell scripts (output means errors).

I've tried to set the log level, but the  server's FrameworkLogger object has no minimumLogLevel property, because it's not subclassed from the Logger class. 

```swift
// this won't work
database.server.logger.minimumLogLevel = 100
```

I also tried to reach the FrameworkLogger's logger property but that's defined as an internal variable.

```swift 
// this won't work either, and it seems like really weird
database.server.logger.logger.minimumLogLevel = 100
```

There should be an option to override the default log level, or disable the entire logging subsystem. 

```swift
// proposed solution
database.server.logger.enabled = false // default true
// or this should delegate the minimum log level property to the underlying logger class
database.server.logger.minimumLogLevel = 100
```

I know that LogKitten handles the logging, but I raised the issue here, because it's related to MongoKitten, maybe LogKitten should be changed as well, it depends on your design.

**Comment by Joannis** [comment]
Try this:

```swift
import LogKitten

Logger.default.minimumLogLevel = 0
```

**Comment by tib** [comment]
It worked, thank you. You should mention this in the docs somewhere. I could not find it.

**Comment by Joannis** [comment]
I will do that!

**Comment by Joannis** [comment]
We're replacing LogKitten with a logging protocol for MongoKitten 4 which includes disabling. I'll keep this issue open since it needs to be added to the tutorials/docs.
