### ISSUE TITLE
Mongo Cursor Iteration is very slow

### ISSUE THREAD

**Issue by sujaykakkad** [OpenKitten/MongoKitten#106]
Ok I have a collection which has over 100000 documents. 
I just want to iterate over the all documents once
So I wrote a simple program to iterate
```swift
import MongoKitten
import Foundation

let server = try Server(mongoURL: "mongodb://localhost")
let database = server["samespace_dev"]

let now = Date()
let cursor = try database["collection"].find()

var arr: [Document] = []
for document in cursor{
    arr.append(document)
}

print(Date().timeIntervalSince(now))
```
I just printed the start time and end time. The iteration took over 186 seconds(over 3 minutes).
I guess the driver is converting to document type everytime which is making iteration slow. Is there a faster way to iterate. I just ran a basic find query in node and it took only 5 seconds. I just want to take documents from one collection do some changes and insert to another collection.

**Comment by Joannis** [comment]
MongoKitten 4 will improve the performance of this drastically. I would suggest mutating and updating the document in the `for .. in cursor` loop. I think you'll be draining a lot of performance by storing everything inside `arr`.

If you insist on using `arr` in the middle I'd suggest `Array(cursor)`

**Comment by sujaykakkad** [comment]
I also tried doing it without array
Simple basic loop without assigning anything
```swift
import MongoKitten
import Foundation

let server = try Server(mongoURL: "mongodb://localhost")
let database = server["samespace_dev"]

let now = Date()
let cursor = try database["carriers_rates_outbound"].find().map({
    _ in
})

print(Date().timeIntervalSince(now))
```

Still it took over 3 minutes(189 seconds). I also tried ```swift Array(cursor)``` it takes the same time.

**Comment by sujaykakkad** [comment]
I also tried with 25000 records example set given in mongodb documentation the link is below.
https://docs.mongodb.com/getting-started/shell/import-data/
While releasing Mongokitten 4 please test it with this data set.
The basic loop for this is taking over 21 seconds. I tested the same in node and it took around 0.8 seconds.

**Comment by Joannis** [comment]
Let me look into this! I'll test it today

**Comment by Joannis** [comment]
I didn't test it in MongoKitten 3 to verify your problem. MongoKitten 4 is iterating lazily over 30k documents in 500ms on my macbook.

With my next cursor enhancement it will be proactive rather than lazy.

**Comment by Joannis** [comment]
The above enhancement, by the way, will improve performance of active iterations (almost all iterations)

**Comment by sujaykakkad** [comment]
Well that's great if it is faster than node. Also can you test it on mongokitten 3?

**Comment by sujaykakkad** [comment]
Also were those 30000 records from the example dataset whose link I had given?

**Comment by sujaykakkad** [comment]
Also were those 30000 records from the example dataset whose link I had given?

**Comment by Joannis** [comment]
No, it was another dataset. Your dataset took 650ms.

**Comment by Joannis** [comment]
And with my local patch 120ms for your dataset. 80ms for my dataset.

**Comment by sujaykakkad** [comment]
Oh that is fast. So it was done in MongoKitten 4. So when are u releasing MongoKitten 4?

**Comment by Joannis** [comment]
Whenever Vapor releases their new TLS library.

**Comment by Joannis** [comment]
I got fed up waiting. If you use the `4.0.0-vaportls` tag you'll be fine using the normal SSL library. I'll be replacing it in the coming `majorVersion: 4` tag

**Comment by mgiroux** [comment]
This is still a problem in version 4 i am loading about 40 records and it takes 10-12 seconds.. it's ridiculously slow

**Comment by Joannis** [comment]
@mgiroux are you sure this is MongoKitten being slow? I'm fetching hundreds of thousands of records/second if I try to stress it.

**Comment by Joannis** [comment]
What kind of records are you downloading? Can you give some more details?

**Comment by mgiroux** [comment]
im downloading records that have about 12-15 properties. From that im fetching its owner (another document) and "replies" which are documents of the first type and it's owners.. so let's say im doing about 10-15 calls (that requests about 20-25 record per call) and with Redis i get 4.5sec for that. without it's passed 10 seconds.

**Comment by mgiroux** [comment]
i ran a simple test.. 10 000 records, 4 seconds for 10k .. so hundreds of thousands in 1 sec.. very doubtful (on a macbook pro 2015)

**Comment by Joannis** [comment]
Are you running on debug mode? Or release? Because this makes a **huge** amount of difference (upwards of factor 200)

**Comment by mgiroux** [comment]
release

**Comment by riordanwhite-haired6** [comment]
A solution worth seeing https://stackdev.space/questions/exploring-all-data-entries-in-the-collection-using-pymongo
