### ISSUE TITLE
Import .json to create or overwrite collection?

### ISSUE THREAD

**Issue by stvnmcdonald** [OpenKitten/MongoKitten#109]
Does MongoKitten provide functionality to import a .json file to completely replace a Collection? I have three Collections for each new customer DB I create that require data and unique id's (which is why I don't copy or clone a templateDB). I have been using a shell script with mongoimport to achieve this so far. Thanks!

**Comment by Joannis** [comment]
This is currently not possible without `mongoimport`. If you split the file by `\n` you'll get an array of strings. If you pass each string into the extendedJSON initializer you'll get a Document for each entry in this JSON file. These Documents can then be inserted.

For MongoKitten 3 you'll need the json file as a String.
```swift
let fileData: String = ... // string contents of the JSON file
let documents = try fileData.split(separator: "\n").map(Document.init)

try collection.insert(documents)
```

In MongoKitten 4 both String and `[UInt8]` will work:
```swift
let data: Data = ... // contents of the json file
let documents = try data.split(separator: 0x0a).map({ Array($0) }).flatMap(Document.init(extendedJSON: ))

try collection.insert(documents)
```

**Comment by stvnmcdonald** [comment]
Thank you! Can I use MK4 with Vapor 1.5? I came across these docs first and saw it required 2.0 but had not tried. I know it is a beta site.
http://beta.openkitten.org/frameworks/vapor/Vapor/

**Comment by stvnmcdonald** [comment]
Thanks! Upgraded to 4.
