### ISSUE TITLE
ObjectId string only?

### ISSUE THREAD

**Issue by stvnmcdonald** [OpenKitten/MongoKitten#110]
I have the below issue:
 var orgDoc = try organizationCollection.findOne(matching: ["name":customer])
 var orgNew = orgDoc.extract()?.dictionaryValue["_id"]?.makeExtendedJSON()
The result of print is below: 
{"$oid":"58ee953c54847dc3319fd408"}
- but it is as a String and I cannot get only the "58ee953c54847dc3319fd408" value to return. How can I return an objectId as just string from a document after find? Thanks.

**Comment by Joannis** [comment]
ObjectId has a computed property called `hexString` which is what you're looking for. Since you're using MongoKitten 3:

`(orgDoc["_id"] as ObjectId?)?.hexString`

For MongoKitten 4:

`ObjectId(orgDoc["_id"])?.hexString`

**Comment by stvnmcdonald** [comment]
This was exactly what I needed. I really appreciate you taking the time to assist. Thank you!
