### ISSUE TITLE
Docs links are not working

### ISSUE THREAD

**Issue by dsantosp12** [OpenKitten/MongoKitten#112]
In http://mongokitten.openkitten.org/ the links under the "Learn" sections are not working.

These are the link label:
* "We host all our tutorials here"
* "And we host the MongoKitten documentation including dash docset here"

I didn't try anything else. I hope it makes sense.

**Comment by Joannis** [comment]
Ah. I see! Thanks. That page is a copy of the github readme.
http://mongokitten.openkitten.org

It currently points to http://beta.openkitten.org where I'm working on MongoKitten 4 tutorials. By the way, MongoKitten 4 is not in beta, I just didn't move it to a new domain yet.

**Comment by Joannis** [comment]
https://www.reddit.com/r/swift/comments/65bvre/a_rapidly_growing_list_of_mongokittenswift_guides/

I'm going to expand this a lot.

**Comment by dsantosp12** [comment]
Great thanks!
