### ISSUE TITLE
Non-vapor?

### ISSUE THREAD

**Issue by CocoaPriest** [OpenKitten/MongoKitten#113]
The 4.0 version has the "4.0.0-vaportls" tag. Does it mean I have yet to wait for a non-vapor version? (I work with perfect)

**Comment by Joannis** [comment]
`4.0.0-vaportls` is a version of MongoKitten build on vapor/TLS. I'm working with the Perfect and Kitura teams to see what the ideal solution is for MongoKitten SSL support.

**Comment by Obbut** [comment]
MongoKitten 4.0 (without the vaportls suffix) is released which no longer relies on external libraries (except OpenSSL) for TCP/TLS
