### ISSUE TITLE
Can I use this library with iOS?

### ISSUE THREAD

**Issue by bushev** [OpenKitten/MongoKitten#114]
Hello, guys! First of all, thank you for such awesome project.

I'm writing a **MongoDB Administration tool** for Mobile devices. I can't find the **requirements concerning OS**, just Swift 3.1. So, if you can to supplement the requirements it would be great!

Thank you!

**Comment by Joannis** [comment]
Hello @bushev . I'm also writing a MongoDB administration tool, but for macOS. I'm working on this as we speak but am having some problems with SSL connections on macOS and iOS using `Security`

**Comment by Joannis** [comment]
Try the 0.0.30 tag

**Comment by bushev** [comment]
Hi, @Joannis! I'm completely new in Swift, I want to create Cordova plugin using this library for future use with Ionic 3. I will try it since there is a chance to get it works. Thank you!

**Comment by bushev** [comment]
@Joannis, problem like this?

![image](https://cloud.githubusercontent.com/assets/7535766/25868506/95727da2-3505-11e7-90f1-5ce26707779c.png)

**Comment by Joannis** [comment]
Precisely that! If you comment that line it might work on iOS. This line worked on macOS, though.

**Comment by bushev** [comment]
@Joannis, bingo! I not I can connect to my MongoDB from iOS app!

**Comment by AbhishekVashisth** [comment]
Hi Bushev, I am new in Swift, could you please guide me the steps to connect my iOS app with mongoDB through SSH tunnel using OpenKitten/MongoKitten driver. 

Thanks in Advance.

**Comment by Joannis** [comment]
@AbhishekVashisth first you'll need to set up a connection to the remote server using an SSH tunnel. I'm not sure how you plan on doing this on iOS, but I'll leave that up to you. In this example I'm spawning a background SSH connection `fN` will put the connection in the background so I can continue to use or close the shell. `-l` will be the remote Linux server's user that I'm authenticating as. `-i` is the `id_rsa` file that I use to authenticate with using my certificate. `-L` is the actual SSH tunnel. In this case I'm forwarding `localhost:27018` to the remote server's `localhost:27017`. And finally I specify the remote server to connect to.

```
sh -fN -l <remote-user> -i /path/to/id_rsa -L 27018:localhost:27017 <remote-host>
```

After this you can connect to `mongodb://localhost:27018` from your app and add any credentials if necessary.

By the way, Bushev isn't the MongoKitten developer @AbhishekVashisth
