### ISSUE TITLE
How to pass params to the createIndex conditionally?

### ISSUE THREAD

**Issue by bushev** [OpenKitten/MongoKitten#116]
Hi, guys!

I'm tried to create an index with `createIndex`. I don't know all index properties (like `unique`, `sparse`, etc) at a compilation time. So I need to pass these params conditionally.

I Googled about `Variadic Parameters` and how to convert an `Array` to `Variadic Parameters`. But it seems such conversion is not supported in Swift yet (correct me if I'm wrong). Also, I can't find an `apply` function in Swift.

**Comment by Joannis** [comment]
For this reason we have `collection.createIndexes` which is the more "raw" version of `createIndex`.
`createIndexes` will accept an array of indexes.

**Comment by bushev** [comment]
Thank you! 👍
