### ISSUE TITLE
Minimum supported version is 3.0.0?

### ISSUE THREAD

**Issue by bushev** [OpenKitten/MongoKitten#118]
Hello, @Joannis!

README.MD states minimum supported version of MongoDB is **2.6**.

But I can find some commands available since version **3.0.0**, like:

https://docs.mongodb.com/manual/reference/command/listCollections/

So, minimum supported version is 3.0.0, that's correct?

**Comment by Joannis** [comment]
There are also commands like $lookup which are 3.2 and above only and many other features.

We support MongoDB 2.6 and above, but also later versions. We cannot know on compile-time which server version you're connecting to, so we include 2.6, 3.0, 3.2 and 3.4 commands.

**Comment by bushev** [comment]
Thank you!

**Comment by bushev** [comment]
@Joannis , do I have an ability to get collection names from MongoDB v2.6? As I can understand I can't execute mongo shell commands, like https://docs.mongodb.com/manual/reference/method/db.getCollectionNames/ ?

**Comment by Joannis** [comment]
I see, I've tried looking for a solution. But there are _no_ docs on implementing this. Do you know something that I could use for a reference maybe?

**Comment by bushev** [comment]
I'm looking too, I have found, that mongo-c driver [uses](https://github.com/mongodb/mongo-c-driver/blob/r1.6/src/mongoc/mongoc-database.c#L896) quering for [<-database->.system.namespaces](https://docs.mongodb.com/manual/reference/system-collections/#<database>.system.namespaces) to fetch a collections list.

**Comment by Joannis** [comment]
Oh, thanks! I'll fix it for MongoDB 2.6 and give you a heads up when it's implemented

**Comment by bushev** [comment]
Maybe we can also add some interface for accessing any others [Mongo Shell](https://docs.mongodb.com/manual/reference/method/) commands?

**Comment by Joannis** [comment]
(Almost) all of those commands are already available through the Swift API. Or do you mean accessing them using the Mongo Shell syntax (using JSON/JavaScript)?

**Comment by bushev** [comment]
No, not for syntax. I mean accessing commands that are not available using Swift API, methods like `db.getCollectionNames()`.

**Comment by Joannis** [comment]
If you find anything that's not implemented, you can create an issue :)

**Comment by Joannis** [comment]
Collections can be listed in the last commit. Waiting for CI to pass and I'll tag 4.0.7 next.

**Comment by Joannis** [comment]
Tagged

**Comment by bushev** [comment]
Works great!
