### ISSUE TITLE
Milliseconds are truncated

### ISSUE THREAD

**Issue by bushev** [OpenKitten/MongoKitten#119]
Steps to reproduce:

1. Initially, I have a data like: `{"createdAt": "2017-01-17T15:04:20.985Z"}` in my MongoDB.
2. Due to this [`"yyyy-MM-dd'T'HH:mm:ssZZZZZ"`](https://github.com/OpenKitten/MongoKitten/blob/mongokitten4/Sources/ExtendedJSON/ExtendedJSON.swift#L19) formatting application receives Date without milliseconds information.
3. Finally, milliseconds will be lost on save.

From my point of view, it would be great to change the date format to: `"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"` (UTC without a local offset). Like guys from studio3t have implemented in MongoChef. Or just add 'SSS' to the date format string and to your ISO8601 parser.

**Comment by Joannis** [comment]
I'm looking at how I will implement this without breaking expected behaviour for other people. I'll make sure it's possible, though.

**Comment by bushev** [comment]
For instance we can introduce some compilation flag to define that.

**Comment by Obbut** [comment]
We aren't generally fans of compilation flags but a global (runtime) parameter would be an option I think. However, in my opinion this would not be a breaking change, because the output date format is still ISO8601. I'm fine with changing this in a minor.

**Comment by Joannis** [comment]
Cool. I'll be adding this feature to ISO8601's serialiser and parser.

**Comment by bushev** [comment]
It seems it's still not supported.

**Comment by Joannis** [comment]
Latest MongoKitten 4 has it. `swift package edit MongoKitten --revision mongokitten4` will let you use it. I'll tag it soon, but I want one more pair of commits in the next tag

**Comment by bushev** [comment]
Yeah! 👍
