### ISSUE TITLE
Safely sorting array of documents

### ISSUE THREAD

**Issue by sujaykakkad** [OpenKitten/MongoKitten#123]
I have an array of documents and I want to sort them based on some string parameter.
eg:
```swift
let docs: [Document] = [["name": "a"] as Document, ["name": "c"] as Document, ["name": "b"] as Document]

let sortedDocs = docs.sorted(by: {($0[raw: "name"]?.string)! < ($1[raw: "name"]?.string)! })
```
This is working but I have to force cast it with exclamation. Is there a way to gracefully sort the documents.

**Comment by Joannis** [comment]
Yes, although this isn't exactly a MongoKitten/OpenKitten issue. This is part of Sequence and thus the swift language rather than our ecosystem/libraries.

You'll need to either accept in your comparison that either or both of them can be optional, or flatMap the values to type-safety.
