### ISSUE TITLE
Cannot add Int64 values in Document

### ISSUE THREAD

**Issue by sujaykakkad** [OpenKitten/MongoKitten#125]
```swift
let number: Int64 = 4194910943930
let doc = ["large_number": number]
```

It is throwing runtime error
```sh
fatal error: Only [String : BSON.Primitive] dictionaries are BSON.Primitive. Tried to initialize a document using [String : Any]. This will crash on debug and print this message on release configurations
```

**Comment by Joannis** [comment]
Use `Int` instead. `Int64` == `Int` on 64-bit systems.

**Comment by sujaykakkad** [comment]
But If I have a 32bit server then it will be Int32 and that is why I have explicitly declared it as Int64. How can I assure that it will store a 64bit integer not matter what the type of system is (32bit or 64bit)?

**Comment by Joannis** [comment]
I don't think there is any build of Swift I've seen on 32-bits except the raspberry Pi.

**Comment by sujaykakkad** [comment]
Yup I guess I will have no problem in getting Int64 values as all the systems will be 64bit.
