### ISSUE TITLE
[Improvement] Support for `Codable` in Swift 4?

### ISSUE THREAD

**Issue by shanehsu** [OpenKitten/MongoKitten#126]
`Codable` seems to be easier to implement if the user want to read/save with his own custom Swift data type. Off the top of my head, this at least requires a custom implementation of `Encoder` and `Decoder` to directly encode/decode BSON bytes (without writing to a BSON `Document` first)

Any comments and suggestions are welcome!

**Comment by Joannis** [comment]
We already have it, but we're not tagging it yet since the code is messy and Swift 4 is still not a GM.

```
// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.


import PackageDescription

let package = Package(
    name: "Project",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .executable(
            name: "Project",
            targets: ["Project"]),
    ],
    dependencies: [
        .package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 4),
        .package(url: "https://github.com/OpenKitten/BSON.git", .revision("swift4")),
        // Dependencies declare other packages that this package depends on.
    ],
```

As you see, you can explicitly set a branch in Swift 4's SPM, it'll make use of the `swift4` branch of BSON using this, so you can use the `BSONEncoder` and `BSONDecoder`.

Alternatively, you can put the package in editable mode using `swift package edit BSON --revision=swift4`. Either method works, but do regenerate the project afterwards.

**Comment by Joannis** [comment]
Oh, one more thing; Using lazy cursor transforms you can decode BSON documents directly to your models.

```swift
class User : Codable {
  let username: String
  ...
}

let db = try Database("mongodb://localhost/testdb")
let users = db["users"]

let userDocuments = try users.find(...)
let users = userDocuments.flatMap { document in
  return try BSONDecoder().decode(User.self, from: document)
}

for user in users {
  print(user.username)
}
```

**Comment by shanehsu** [comment]
@Joannis Out of curiosity, is this implemented in BSON or MongoKitten? Also, is there a documentation group working on docs? The [link on OpenKitten](http://openkitten.org/docs.html) is unreachable.
Using MongoKitten on my school project, and loving it!

**Comment by Joannis** [comment]
It's implemented in BSON. I've heard and seen that the openkitten website is broken in multiple places. I can't update the website properly since half of my developer tools broken on high sierra. MongoDB, Swift and Xcode still work, though ;)

**Comment by shanehsu** [comment]
Does MongoKitten has complete documentation other than Dash docset? When I started using it, I feel the documentation is quite lacking and disappointing. I had to Google most stuff, or follow the debugger.

**Comment by Joannis** [comment]
Most of it will be explained here: http://beta.openkitten.org . Beta hasn't been moved to http://docs.openkitten.org since I wasn't able to adjust the template yet. I want to have both the MK3 and MK4 docs available, so MK4 is under beta.
