### ISSUE TITLE
Mongo Atlas connection issues on Linux

### ISSUE THREAD

**Issue by chariot6** [OpenKitten/MongoKitten#127]
Attempting to connect to Mongo Atlas with Linux sometimes results in:

```fatal error: Error raised at top level: MongoKitten.MongoError.noServersAvailable: file /home/buildnode/disk2/workspace/oss-swift-3.1-package-linux-ubuntu-16_04/swift/stdlib/public/core/ErrorType.swift, line 1881```

**Comment by plummer** [comment]
Any further updates on this @chariot6 ?

**Comment by plummer** [comment]
Note, immediately after switching from compose to atlas I'm got the error:
`Identifier: Sockets.SocketsError.writeFailed)`
`Server error: dispatch(Sockets Error: Failed to write from socket`

**Comment by chariot6** [comment]
No updates yet. I haven't really had the chance to investigate it, to be honest. If I have the time to spare soon, I'll be sure to post what I find.
---
I haven't tried it with Compose. With Atlas it's pretty random. When I wrapped the connection logic in a do-catch that was nested inside a loop, I think I was running into the error about half of the time.

**Comment by Joannis** [comment]
Hello :) Correct, MongoDB atlas differs from other hosts in that it requires the SNI to be defined. Something I don't think works well on Linux

**Comment by Joannis** [comment]
Should be fixed.

**Comment by natanrolnik** [comment]
Not sure if it’s related, but when I deployed my app to a Linux instance, I had problems connecting to Atlas as well. See #143
