### ISSUE TITLE
Able to connect to Atlas with a wrong password

### ISSUE THREAD

**Issue by bushev** [OpenKitten/MongoKitten#134]
Hello, Joanis!

I able to create a client to MongoDB Atlas even if the password is wrong.

Expected: Connect error
```
{ 
"ok" : NumberInt(0), 
"errmsg" : "bad auth Authentication failed.", 
"code" : NumberInt(8000), 
"codeName" : "AtlasError"
}
```

Actual: Success connect

Code example:

```swift
let server: Server = try! Server("mongodb://user:WRONG_PASSWORD@cluster0-shard-00-00-cgfjh.mongodb.net:27017,cluster0-shard-00-01-cgfjh.mongodb.net:27017,cluster0-shard-00-02-cgfjh.mongodb.net:27017/admin?ssl=true")
        
print("Connected")
print(server.buildInfo)
```

**Comment by Joannis** [comment]
Should work in the latest commit. Will tag 4.0.15 later today

**Comment by shanehsu** [comment]
@bushev Please close the issue if the problem's gone!

**Comment by bushev** [comment]
Yes, it fixed.

**Comment by Joannis** [comment]
@shanehsu You tried contributing to BSON (on a feature that was already completed) and are now contributing here 👍 thank you!

I'm not sure if you've seen our [community section](https://github.com/OpenKitten/MongoKitten#community) or more specifically [our slack](https://slackpass.io/openkitten)? If you're willing to contribute I'm happy to help you get started. I could use some help with MongoKitten 5, which is primarily a big cleanup (mostly internal) release with some performance improvements.
