### ISSUE TITLE
build fail on download dependencies

### ISSUE THREAD

**Issue by Tigleo** [OpenKitten/MongoKitten#136]
MongoDb/AppDelegate.swift:9:8: error: no such module 'UIKit'
import UIKit
       ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/name/Desktop/MongoDb/.build/release.yaml

Why??

**Comment by Joannis** [comment]
This isn't a MongoKitten issue. MongoKitten uses SPM and fetches it's dependencies through that.

If you want to use MongoKitten in a macOS GUI application you'll need to create a project using MongoKitten, generate an xcodeproject using SPM (`swift package generate-xcodeproj`) and add that to your app's .xcworkspace

**Comment by Tigleo** [comment]
so the manual import?

**Comment by Joannis** [comment]
MongoKitten needs to be downloaded using SPM to download the MongoKitten dependencies. If you've got an SPM (Swift Package Manager) project you can generate an Xcode project using the above command. This project can then be added to your app's xcworkspace
