### ISSUE TITLE
Swift Compiler Error 

### ISSUE THREAD

**Issue by viniciusarre** [OpenKitten/MongoKitten#137]
Hello. I'm running xCode 8.3.3 and Swift 3.1 and I'm developing for universal targets.

Every time I tried using it (I even followed a tutorial on "https://medium.com/@joannis.orlandos/setting-up-mongokitten-4-9a8bf8b2ad09"), I get a Swift Compiler Error in the MongoSocket Target right in this line:

`guard SSLSetCertificateAuthorities(context, cert, true) == 0`, which is nested in 
`
 if let path = options["CAFile"] as? String, let data = FileManager.default.contents(atPath: path) {
                    let bytes = [UInt8](data)
                    
                    if let certBytes = CFDataCreate(kCFAllocatorDefault, bytes, data.count), let cert = SecCertificateCreateWithData(kCFAllocatorDefault, certBytes) {
                        guard SSLSetCertificateAuthorities(context, cert, true) == 0 else {
                            throw Error.cannotConnect
                        }
                    }
                }
`

Please, could you look into it as soon as possible? I need to integrate this for next week... 

Thanks in advance!

**Comment by Joannis** [comment]
Are you compiling MongoKitten for iOS? It's not recommended ( as I mentioned in #138 ).

Otherwise, the code you pointed to actually has a bug (and is not adding functionality). So I'm tagging a version without that code once the unit tests are verified on macOS and Linux.

**Comment by viniciusarre** [comment]
Oh ok, I'm quite new to Swift, could you give me a hint on how I would do that without compiling it?

**Comment by Joannis** [comment]
You can't. Swift is a compiled language. But are you using MongoKitten for iOS?

**Comment by viniciusarre** [comment]
Yes

**Comment by viniciusarre** [comment]
Could you show me an example on how it would work?

**Comment by Joannis** [comment]
It would work with the code I'm pushing once the CI is showing a success.

But why are you running MongoKitten on iOS, if I may ask?

**Comment by viniciusarre** [comment]
Well, I am developing an app which I want to connect with a mongodb database... I got it that I can't compile it to the project directly, but I don't know how not  to... I'm quite new to Swift and I need to get this integration out of the way...

**Comment by viniciusarre** [comment]
Since I have a complex back-end to my project, I believe that mongo is the database that best fits its needs...

**Comment by Joannis** [comment]
Tagged as 4.0.15
