### ISSUE TITLE
The MongoDB response wasn't expected. [{"code":13,"ok":0.0,"errmsg":"not authorized on XXX

### ISSUE THREAD

**Issue by duncangroenewald** [OpenKitten/MongoKitten#139]
This error occurs when trying to connect to a MongoDB v2.6.12 database.  

Using the same credentials works fine using Studio 3T and when connecting to a MongoDB v3.4 database.

**Comment by Joannis** [comment]
MongoKitten doesn't support MongoDB 2.6 as it's not supported by MongoDB itself either. We can technically communicate with MongoDB 2.6 but many issues are really tough to fix or support for MongoDB 2.6.

**Comment by Joannis** [comment]
What authentication mechanism are you using? This issue specifically should be working, though. It's likely regression due to the inability to actively test this feature for 2.6.

**Comment by Joannis** [comment]
If anyone is having these issues with MongoKitten in the future, please create a new issue 👍
