### ISSUE TITLE
Not able to successfully set up MongoKitten

### ISSUE THREAD

**Issue by meghanarora** [OpenKitten/MongoKitten#140]
I have not yet been able to successfully set up MongoKitten on my swift app, when building I get the following error.

any idea what may be causing this?

<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Auth/Database+Authentication.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Auth/SCRAM.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Collection/Collection+Administration.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Collection/Collection+Geospatial.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Collection/Collection.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Database/Database+Administration.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Database/Database+RoleManagement.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Database/Database+UserManagement.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Database/Database.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Error/CRUDError.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Error/MongoError.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Helpers/Bool+String.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Helpers/BuildInfo.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Helpers/Concern.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Helpers/GeoNearOption.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Helpers/Helpers.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Helpers/LogDestination.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Helpers/SerializationHelpers.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Helpers/String+MongoKitten.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Internals/Document+CustomValueConvertible.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Internals/Flags.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Internals/Message.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Internals/MongoDriverInformation.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Internals/OperationCode.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Querying/Cursor.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Querying/DBRef.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Querying/GridFS.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Querying/Index.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Querying/PipelineBuilder.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Querying/Projection.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Querying/QueryBuilder.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Querying/Sort.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Server/ClientSettings+URL.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Server/ClientSettings.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Server/Server.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Server/SSLSettings.swift'
<unknown>:0: error: no such file or directory: '/Users/Meghan/Desktop/Swift Practice/TestMongo/Packages/MongoKitten-3.2.3/Sources/MongoKitten/Socket/Connection.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by Joannis** [comment]
How did you attempt to install/add MongoKitten?

**Comment by meghanarora** [comment]
I added it to Package.swift and did an update

**Comment by Joannis** [comment]
What did you add to Package.swift? Just so I can reproduce it.

**Comment by meghanarora** [comment]
![screen shot 2017-09-23 at 12 11 43 am](https://user-images.githubusercontent.com/12651785/30769988-cf122dba-9ff3-11e7-893a-ca227754f681.png)

**Comment by Joannis** [comment]
Which Swift version is this? MongoKitten 3 was written for Swift 3.0 and above. The Package.swit looks fine. But the behaviour looks like Swift 2.x.

**Comment by Joannis** [comment]
Is this still an issue?
