### ISSUE TITLE
Add support for QueryFlag bit 2

### ISSUE THREAD

**Issue by flufff42** [OpenKitten/MongoKitten#141]
While attempting to use MongoKitten to query a replica slave I ran into the following error:

```
MongoKitten.MongoError.invalidResponse([{"code":13435,"ok":0.0,"errmsg":"not master and slaveOk=false"}])
```
The solution for which according to the [MongoDB Wire Protocol](https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/index.html) documentation would be set the following bit in the operation flags:

> 2 corresponds to SlaveOk.Allow query of replica slave. Normally these return an error except for namespace “local”.

As a workaround I manually added this in 
https://github.com/OpenKitten/MongoKitten/blob/aae045103928b2928b1599dedde2c0b29f58ff50/Sources/MongoKitten/Database/Database.swift#L221 as follows:
```
let commandMessage = Message.Query(requestID: server.nextMessageID(), flags: [QueryFlags(rawValue: 4)], collection: cmd, numbersToSkip: 0, numbersToReturn: 1, query: document, returnFields: nil)
```

There's also some TODOs around the setting on `Server`
https://github.com/OpenKitten/MongoKitten/blob/aae045103928b2928b1599dedde2c0b29f58ff50/Sources/MongoKitten/Server/Server.swift#L105-L109
however I couldn't find an issue or PR noting issues faced while implementing this.

If there's nothing blocking adding support for this I could prepare a PR.

**Comment by Joannis** [comment]
Thanks for such a complete, well researched issue. Really well done! I'd love to see a PR 👍
