### ISSUE TITLE
Git tag confusion

### ISSUE THREAD

**Issue by flufff42** [OpenKitten/MongoKitten#146]
I have been attempting to use MongoKitten for some scripting, in particular with https://github.com/JohnSundell/Marathon

It seems that there are some old tags `5.0.0-beta1` and `5.0.0-obbut2` that don't seem to match the current GitHub releases.

However these cause some issues with tools using git tags to identify the most recent release.
Would it be possible to delete these tags?

**Comment by Joannis** [comment]
Oh, definitely! I'll delete them right now 👍

**Comment by Joannis** [comment]
Fixed 👍
