### ISSUE TITLE
Weight not supported for text indexes

### ISSUE THREAD

**Issue by plummer** [OpenKitten/MongoKitten#149]
Hey @Joannis,

I noticed weights are not supported for text indexes. I thought I can do a PR to fix this up, but there seems to be a note about it above. Any brief details you want to shoot over before I create one to potentially avoid some incorrect / wasted work?

https://github.com/OpenKitten/MongoKitten/blob/7cece593d3421f103cbb183b15f8091218fd72a2/Sources/MongoKitten/Querying/Index.swift#L139

Thanks

**Comment by Joannis** [comment]
I don't think there's anything special you'd need to know. A PR would be awesome!
