### ISSUE TITLE
Doing a find() to contain a substring (contains)

### ISSUE THREAD

**Issue by burf2000** [OpenKitten/MongoKitten#151]
Hi there

How would you do the following mongo statement in MongoKitten
db.users.findOne({"username" : {$regex : ".*son.*"}});

This looks for the word "son" in a string

**Comment by Joannis** [comment]
Sorry, we've missed this issue. If anyone wonders: You need to create a BSON `RegularExpression` object, or use the static helper functions on `Query`.
