### ISSUE TITLE
The operation couldn’t be completed. (Schrodinger.ManualPromise<MongoKitten.ServerReply>.Error error 0.)

### ISSUE THREAD

**Issue by burf2000** [OpenKitten/MongoKitten#155]
Can anyone tell me what this error means? is it a timeout?

The operation couldn’t be completed. (Schrodinger.ManualPromise<MongoKitten.ServerReply>.Error error 0.)

**Comment by Joannis** [comment]
There's an error nested in there which doesn't have a description yet. You can print it from the debugger to figure out what the error is.

**Comment by burf2000** [comment]
Thanks again :)

**Comment by Joannis** [comment]
NIO has different/better errors. Closing this :)
