### ISSUE TITLE
Swift 4.1 warnings persist in latest release

### ISSUE THREAD

**Issue by KyeMaloy97** [OpenKitten/MongoKitten#164]
Hello,

The latest release has a lot of warnings coming from both some external libraries (Cheetah, BSON etc) and also from MongoKitten itself. Is there any plan to fix these? I saw 4.1 was in the latest release log but if I clone that and build it on Swift 4.1 I still get the warnings.

Thank you!

**Comment by Joannis** [comment]
It's not possible to fix these warnings in MongoKitten 4 since it would mean breaking all compatibility with older Swift versions for existing users. MongoKitten 5 will be Swift 4.1+ only and will not have these warnings.

**Comment by KyeMaloy97** [comment]
On our projects to maintain backwards compatibility, we tend to put the code in compiler if swift blocks like:

#if swift(>=4.1)
//do 4.1 code]
#else 
//do 4.0.3 and below code
#endif

**Comment by Joannis** [comment]
Considering the cause and locations of the warning this'll be a major maintainance burden

**Comment by KyeMaloy97** [comment]
That's a fair point, I will close this issue then. Thank you!
