### ISSUE TITLE
NotMasterNoSlaveOk

### ISSUE THREAD

**Issue by valeriomazzeo** [OpenKitten/MongoKitten#167]
I keep randomly getting this error, not sure what could be the cause:

`MongoKitten.MongoError.invalidResponse([{\"ok\":0.0,\"codeName\":\"NotMasterNoSlaveOk\",\"errmsg\":\"not master and slaveOk=false\",\"code\":13435}])`

Environment:
- Mongodb 3.4.14 (Cloud Atlas)
- MongoKitten 4.0.19

**Comment by Joannis** [comment]
@valeriomazzeo It seems MongoKitten sent a query to one of the slaves. This is only possible for read queries where slaveOK is explicitly true. MongoKitten never sets slaveOK to true, so that explains the error. What query were you running?

**Comment by valeriomazzeo** [comment]
I am not sure, as I was using Fluent, so this must be coming from the driver.
Also, restarting the web server fixed the issue. Any idea?

**Comment by valeriomazzeo** [comment]
ok, so how could we prevent this to happen or to properly recover?

**Comment by valeriomazzeo** [comment]
@Joannis ?

**Comment by Joannis** [comment]
You can shutdown MongoKitten's server object and it'll reconnect the next query.

**Comment by valeriomazzeo** [comment]
I suppose when using mongo-driver with fluent it should be the driver to take care of this?

**Comment by Joannis** [comment]
The Fluent driver, yes.

**Comment by Joannis** [comment]
I'm closing this, since it's a Fluent issue.
