### ISSUE TITLE
Support DNS Seedlist Connection Format

### ISSUE THREAD

**Issue by Dev1an** [OpenKitten/MongoKitten#172]
Looking at the following lines, it seems that the DNS Seedlist connection format isn't supported yet.
https://github.com/OpenKitten/MongoKitten/blob/10f7befcdfac18cad8a752d6a6dd950512eb0151/Sources/MongoKitten/ConnectionSettings.swift#L126-L128

Are there any plans to support this feature? It is documented at: https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format

**Comment by Dev1an** [comment]
I made a free cluster using https://cloud.mongodb.com and gives me the following connection uri: `mongodb+srv://<USERNAME>:<PASSWORD>@cluster0-5nnms.gcp.mongodb.net/test?retryWrites=true`

So I guessed the host name would be: cluster0-5nnms.gcp.mongodb.net. But if I do an `nslookup cluster0-5nnms.gcp.mongodb.net` using the terminal I get: Non-authoritative answer:

    *** Can't find cluster0-5nnms.gcp.mongodb.net: No answer

So I have no idea how to get it to work...

**Comment by Dev1an** [comment]
OK, I dug a bit further and wile looking at the [nodeJS implementation](https://github.com/mongodb/node-mongodb-native/blob/78f69774ea45fb1e130eebb7e4bce54205296a8f/lib/url_parser.js#L43-L44) of the connection URI parser. I found out that one has to prefix the host in the `mongo+srv` uri with `_mongodb._tcp.`

So if you want to find out the hosts of your cluster, the nslookup command should look like:

    nslookup -querytype=srv _mongodb._tcp.<host from mongo+srv:uri>

and this should give you back a list of

    <request>	service = <priority> <weight> <port> <host>

**Comment by Joannis** [comment]
Hello @Dev1an, as it happens I've been discussing this implementation with one of the MongoDB leads. The problem isn't necessarily the SRV implementation but the failover to the other cluster nodes using SDAM.

**Comment by Dev1an** [comment]
Yes indeed that is the other part of connecting to a cluster... What is the problem with SDAM?

**Comment by Joannis** [comment]
The problem is testing if it's working after implementing it. The previous time we implemented switching within a cluster the code was a mess (mind you, this was before MongoDB started their spec repo) and we weren't able to verify if it's working in real life scenarios. The limited test scenario we had showed it worked, but as @valeriomazzeo can confirm, this was far from always the case.

**Comment by Joannis** [comment]
This is almost ready in MongoKitten 5.

**Comment by Joannis** [comment]
We're stuck on the implementation because we're unable to call `res_init` [here](https://github.com/OpenKitten/NioDNS/blob/master/Sources/CResolvHelpers/CResolvHelpers.c) because of a linker error. If anyone knows how to solve this, your help is *very* welcome!
