### ISSUE TITLE
Swift 4.2 modifications

### ISSUE THREAD

**Issue by kumarmuthaiah18** [OpenKitten/MongoKitten#177]
Hey humans. Joannis Orlandos  how are you? When we can expect Swift 4.2 modifications. The Apple Xcode compiler is throwing lots of warnings and there is possibility Apple will reject our applications if we not modify Mongo Kitten to latest Swift 4.2. Waiting for it.

**Comment by Joannis** [comment]
Hello. We're aware of the warnings, but we can't change the existing codebase without breaking existing projects that were built in Swift 3.x. We're working on 5.0 and expect to complete the last features this sunday. Why would Apple reject your software? Are you building an iOS app with MongoKitten?

**Comment by kumarmuthaiah18** [comment]
Yes both iOS app and Kitura based web server

**Comment by kumarmuthaiah18** [comment]
Great Joannis! Waiting for version 5.0

**Comment by Joannis** [comment]
I'm not exactly sure what your setup is. But integrating a MongoDB client into an iOS app requires credentials to be known to the app. If you put your MongoDB credentials in the app's binary this is a major security leak. If MongoKitten is being used from Kitura however or your app is a MongoDB client for users, I understand 👍

**Comment by kumarmuthaiah18** [comment]
Dynamic authentication using iOS app as client. Mongo kitten is used from Kitura. Mongo kitten have support for Mongo Mobile? would be better, else I need to use SQL lite? This is separate question.

**Comment by thevojacek** [comment]
It would have been nice to have MongoKitten Swift 4.2 compatible anyways as next release of Swift's compiler will drop support for Swift 3.x anyways.

**Comment by Joannis** [comment]
We're lacking the time do implement the last feature for MK5, which will be Swift >= 4.1. That's the main blocking part right now. We want to add better clusters support with failover and discovery.

**Comment by Joannis** [comment]
MK5 has been released, @kumarmuthaiah18 we do have mobile support in beta
