### ISSUE TITLE
How to use connection pool with MongoKitten 4

### ISSUE THREAD

**Issue by wenxini234** [OpenKitten/MongoKitten#179]
How to use connection pool with MongoKitten 4?

eg:  let db = try MongoKitten.Database(Constants.mongoUrl)

**Comment by Joannis** [comment]
Sorry about the late reply, we completely missed this. MongoKitten has it's own internal connection pool, so you don't need to worry about this at all.

**Comment by wenxini234** [comment]
> Sorry about the late reply, we completely missed this. MongoKitten has it's own internal connection pool, so you don't need to worry about this at all.
Thank you very much for your reply
