### ISSUE TITLE
Xcode 10.2 not able to use MongoKitten 4

### ISSUE THREAD

**Issue by kumarmuthaiah18** [OpenKitten/MongoKitten#196]
**Describe the bug**
Xcode 10.2 not able to use MongoKitten 4. Used Toolchain in Xcode and selected Swift 4.2.3, but issue is coming while building code. Also used MongoKitten 5, but issues coming in Mac OS, so need to depend on MongoKitten 4. MongoKitten 5, I hope developed only for Ubuntu and other Linux varieties. If we ignore some other platforms then it can affect the developer who depend on MongoKitten. Open source component if created for servicing peoples, then it should be serviced until end.

**To Reproduce**
Install latest Xcode 10.2 with all install Xcode requested. Create a library with mongo kitten 4 using package manager. Try to build using Xcode UI

**Expected behavior**
Successful completion of build

**Server-side Swift:**
 - OS: macOS
 - Swift Version: 4.2.3
 - MongoKitten  Version 4.0.0

**Mobile:**
 - Swift Version: [e.g. 4.2]
 - MongoKitten Version [e.g. 5.1.1]

**Additional context**

**Comment by Obbut** [comment]
> Also used MongoKitten 5, but issues coming in Mac OS, so need to depend on MongoKitten 4. MongoKitten 5, I hope developed only for Ubuntu and other Linux varieties. If we ignore some other platforms then it can affect the developer who depend on MongoKitten. Open source component if created for servicing peoples, then it should be serviced until end.

What do you mean? We support macOS with MongoKitten 5 just like we support macOS in MongoKitten 4. In fact, we have much better platform support in MK5.

**Comment by kumarmuthaiah18** [comment]
Issues coming Obbut. What can I Do!

**Comment by Joannis** [comment]
We're using MacOS Mojave almost exclusively at the moment, so yes.

**Comment by kumarmuthaiah18** [comment]
Joannis what are the steps to migrate to MK 5? Any document is there?

**Comment by Joannis** [comment]
There's no document for the migration. But making one would be extremely challenging considering the introduced dependency and heavy usage of SwiftNIO. A 1:1 guide would only be doable using by `wait()`-ing on a Future.

**Comment by kumarmuthaiah18** [comment]
If we look into customer perspective, have you not considered the risk in the beginning. If we release new versions the migration should be smooth for the customer, who heavily trust you. You need to provide plan support in the beginning of the development before releasing new versions that includes documentation whether it is complicated or not.

**Comment by kumarmuthaiah18** [comment]
I don't really like software companies whether free or not, always ignore documentation. Nobody understands technical things which are not human friendly. Only documentation can help all peoples of different skills. If we are not preparing documentation no need to develop software in first place.

**Comment by Obbut** [comment]
I think you do not fully understand how open source software works. You are not a customer, and we are not a company.

You are a user of an open source library that was developed mainly by @Joannis and me, as a hobby project and out of love. We don't have to provide any form of support.

**Comment by kumarmuthaiah18** [comment]
Obbut, so its time for the open source software rules to change! If you develop some house for free and let tenants live there, and say it is free we are no obliged to support. I don't think it is humanly.,

LOVE you don't understand its meaning. "We don't have to provide any form of support" really? Then what is the use of your free software in first place? If support is conditional, then it is not free, it is cheating.

**Comment by kumarmuthaiah18** [comment]
You are not showing real LOVE!

**Comment by kumarmuthaiah18** [comment]
If free software is like this then people will move to paid software with real support. What is the use of free software?
