### ISSUE TITLE
Query Builder Syntax

### ISSUE THREAD

**Issue by panigrah** [OpenKitten/MongoKitten#200]
Hi, I am migrating to MongoKitten from a different library that had supported query chaining to create queries dynamically. I am struggling to figure out how best to do that in MongoKitten. So I could do something like 

`query = Query().where(field1, value1).where(field2, value2).where(field3, value3)` 

fieldN and the valueN would be dynamically provided by the user to create arbitrary filters.

Whats the best way to create this dynamically in MongoKitten.

thanks for the help.

**Comment by Joannis** [comment]
We have the `&&` and `&&=` operators for that

```swift
var query: Query = ("username" == "Panigrah" && "active" == true)

for (field, value) in queryMatches {
query &&= (field == value)

collection.find(query).limit(25).skip(50).getAllResults()
```
