### ISSUE TITLE
How do I get the inserted document Id?

### ISSUE THREAD

**Issue by smbhuin** [OpenKitten/MongoKitten#204]
Hi,

In MongoKitten 5, How do I get the inserted document Id in `whenSuccess` block?

**Comment by Andrewangeta** [comment]
I was just deciding how to do this for myself. Luckily I have unique information per insert which I can query back. But alternatively you can generate the ObjectID before you insert. And request that based on that ID

**Comment by smbhuin** [comment]
Okay then I have to generate the ObjectID before insert. Thx.
