### ISSUE TITLE
Check if collection exists

### ISSUE THREAD

**Issue by Lupurus** [OpenKitten/MongoKitten#212]
I didn't found a way how to check, if a collection really exists, becaue calling `myDatabase.collection["myCollection"]` doesn't return an Optional (I guess, that MongoKitten will create the collection if I would do any create actions there?).

My way is now the following, but I wanted to ask, if there is a better solution:

```
extension Array where Iterator.Element == MongoCollection {
	subscript(name: String) -> MongoCollection? {
		return self.first { collection -> Bool in
			return collection.name == name
		}
	}
}

myDatabase.listCollections().whenComplete { result in
	if case .success(let collections) = result {
		if let myCollection = collections["myCollection"] {
			...
		}
	}
}
```

**Comment by Joannis** [comment]
Yeah, MongoKitten creates the collection if it doesn't exist yet. The above solution seems good to me. Maybe we can add a helper to fetch the existence of a single collection, but I doubt that there's a large added benefit.

**Comment by Lupurus** [comment]
Hey, thanks for the answer. Why would there be no benefit? The reason, why I am doing this, is checking at the startup, if all the databases, that my server needs, really exists. If not, I don't want, that my server starts (or I could recreate them maybe).

**Comment by Joannis** [comment]
I think so because MongoDB automatically creates the databases and collections when needed. The only problem might be creating the indexes. I do that using a migrations collection

**Comment by Lupurus** [comment]
Hm, I think you're right... I thought about it and it's maybe a thinking error of me. MongoDB is not like SQL, the collection doesn't need to exist before, because I can create the contents later (and I don't need to create a table for it). So maybe I thought too far. But thanks anyway for your (fast) response and help :)
