### ISSUE TITLE
[v6] Can't fetch more than 100 items

### ISSUE THREAD

**Issue by vim-zz** [OpenKitten/MongoKitten#217]
I have the following code working with v5:

```swift
     do {
        let db = try Database.synchronousConnect(mongo_link)
        
        let collection = db[collection_name]
        collection.find().forEach {
            debugPrint("Adding \($0)")
        }.wait()

    }
    catch {
        debugPrint("Unexpected error: \(error).")
    }
```

Now, when I try to do the same with v6 it doesn't work... as it crash. If I omit the .wait() I get only the first 100 entries. 

```swift
     do {
        let db = try MongoDatabase.synchronousConnect(mongo_link)
        
        let collection = db[collection_name]
        collection.find().forEach {
            debugPrint("Adding \($0)")
        }
       //.wait() <--- crash 

    }
    catch {
        debugPrint("Unexpected error: \(error).")
    }
```

**Comment by Joannis** [comment]
I think you're trying to use `.wait()` from within an eventloop, hence the crash. NIO is not crashing as a bad thing, it crashing it a really good thing as the alternative would be to deadlock the thread.

I'm surprised `.wait()` worked for you in v5. To me it indicates your codebase changed quite a lot.

I can imagine that you're only getting the first 100 entries since your database object (`db`) is not captured elsewhere in memory. So it'll be deinit-ed and deallocated pretty quickly.

**Comment by vim-zz** [comment]
@Joannis any suggestions for what should I do?

**Comment by Joannis** [comment]
```
enum Constants {
    static let db = try! MongoDatabase.synchronousConnect(mongo_link)
}
```

You could try doing something like this, but my suggested solution strongly depends on what you're trying to do.

**Comment by vim-zz** [comment]
Well, I simply need to read once an entire collection from mongo. I also don't use NIO (or at least explicitly) I just need a simple blocking call to mongo database that fetches all the entries in a certain collection. that's it. 

With v6 I only got the first 100 and can't get the rest. With v5 it works.

**Comment by Joannis** [comment]
@vim-zz did you try my suggestion? I'm pretty sure that your database connection is closed because it wasn't being retained.

**Comment by vim-zz** [comment]
@Joannis yes, i tried adding it as static var to the class I am using, then calling it the same way, but it gave me the same result.

**Comment by Joannis** [comment]
Do you just run `debugPrint("Adding \($0)")` per Document? Or do you have other (error-throwing) logic in there?

**Comment by vim-zz** [comment]
I have other logic, that adds each item to a collection.

**Comment by Joannis** [comment]
Could the logic be throwing an error, by any chance?

**Comment by Joannis** [comment]
Could you share the logic you're using? I might see why that could be causing a crash if you're doing `collection.insert(document).wait()`

**Comment by vim-zz** [comment]
I have removed the other code, still same problem. I don't use NIO (or at least as far as I am aware of). This is the whole snippet:

**Comment by Joannis** [comment]
NIO is involved wherever you see `EventLoopFuture` in MongoKitten's APIs.
In your example I can imagine that `RealThing.self` fails to decode somewhere in your collection, and therefore the cursor fails decoding further.

**Comment by Joannis** [comment]
Is there a specific error that you're seeing?

**Comment by vim-zz** [comment]
I get "Unexpected error: An optional was unwrapped but `nil` was found."

I will check the decode part, it might be the problem

**Comment by vim-zz** [comment]
@Joannis can I call the decoder inside the loop somehow? So I can `try` the decoding

**Comment by Joannis** [comment]
```swift
cursor.map { document in
    return try decoder.decode(RealThing.self, from: document)
}
```

The above should do the stick!
