### ISSUE TITLE
find -> sort : response time very slow

### ISSUE THREAD

**Issue by ViewDidLoad** [OpenKitten/MongoKitten#220]
collection count : 1,200,000

mongo shell command
> db.find({TRN_NO: “\(trn_no)”}).sort({_id: -1}).limit(1)
response time : 200ms

MongoKitten
let FindResults = collection.find("TRN_NO" == “\(trn_no)").sort(["_id":.descending]).limit(1).getAllResults()
response time : 18,000ms

What did I do wrong?
How can I get code to get a quick response?

**Comment by Joannis** [comment]
The only thing I can imagine is that for this query, MongoKitten didn't yet create an authenticated connection to the database. Probably because you used `lazyConnect` to create an instance.
Successive calls should be far better.

**Comment by ViewDidLoad** [comment]
main.swift
let worker_user = "worker"
let worker_passwd = "worker_passwd**"
let worker_db = try Database.synchronousConnect("mongoldb://\(worker_user):\(worker_passwd)@127.0.0.1:27017/worker_db

worker_handler.swift
let FindResults = collection.find("TRN_NO" == “(trn_no)").sort(["_id":.descending]).limit(1).getAllResults()

Very slow
I guess it seems to sort all the data in the collection after importing it.
Am I using it wrong?

**Comment by Joannis** [comment]
How large is the dataset? I think your problem might be that `getAllResults` loads all results into a large array (in memory). If your dataset is bigger than 500 documents, definitely look into another implementation that uses `forEach` or `sequentialForEach`.

**Comment by ViewDidLoad** [comment]
Thank you for the response.
I solved the problem in another way.
The query was so slow that I solved it by taking the entire result, storing it in an array and processing it.
The entire array of results is updated periodically.
