### ISSUE TITLE
How should we use change streams in 6.0?

### ISSUE THREAD

**Issue by Dev1an** [OpenKitten/MongoKitten#226]
It looks like there is no obvious way to get notifications from a change stream. Up to 51fa7160ab4e96d7148fb7cd7b7244b88b04dea2 there was a [forEach](https://github.com/OpenKitten/MongoKitten/blob/51fa7160ab4e96d7148fb7cd7b7244b88b04dea2/Sources/MongoKitten/ChangeStream.swift#L112-L114) method on the [ChangeStream](https://github.com/OpenKitten/MongoKitten/blob/51fa7160ab4e96d7148fb7cd7b7244b88b04dea2/Sources/MongoKitten/ChangeStream.swift#L97) stuct:

https://github.com/OpenKitten/MongoKitten/blob/51fa7160ab4e96d7148fb7cd7b7244b88b04dea2/Sources/MongoKitten/ChangeStream.swift#L112-L114

But after e78e5b0c1229ddec0d9eafbcf747a439d3cbfca2 it has dissapeared and never came back.

Since the [cursor](https://github.com/OpenKitten/MongoKitten/blob/b5d3975737f55528b048143798e06587041e0d40/Sources/MongoKitten/ChangeStream.swift#L46) is internal we cannot use that either. 

https://github.com/OpenKitten/MongoKitten/blob/b5d3975737f55528b048143798e06587041e0d40/Sources/MongoKitten/ChangeStream.swift#L46

So how can we handle change notifications in MongoKitten 6.0?

**Comment by Andrewangeta** [comment]
CC @Joannis

**Comment by Joannis** [comment]
Hey @Andrewangeta thanks for notifying me, I missed this.
The change stream API had some serious reliability bugs if I remember that correctly. I've reimplemented it but never tagged it [until 6.2.0](https://github.com/OpenKitten/MongoKitten/releases/tag/6.2.0).
