### ISSUE TITLE
How can I reference("relation") two or more documents? :D

### ISSUE THREAD

**Issue by jacrack** [OpenKitten/MongoKitten#236]
Hi, im new in this..

I want to know how can I refer two or more documents like:
`
{ // Document User
   id: id
   user: "lala"
}

{ // Document Product
    id: id
    product: "laptop"
}

{ // Document Sales
    id: id
    user: reference<user>
    product: reference<product>
    price: 323432
   etc...
}
`

Thanks :D

**Comment by Joannis** [comment]
If your documents are using `ObjectId` you can store that ObjectId in the other entity. So `user: reference` would be `user: ObjectId`.
In addition to that, you can use the Meow APIs for modelling your data. This contains a `Reference` type that can refer to another `Model` which looks like this: `let product: Reference<Product>`
