### ISSUE TITLE
Error "require macos 10.10 or earlier" but my macos version is 10.15.5

### ISSUE THREAD

**Issue by heart** [OpenKitten/MongoKitten#251]
Hello I using MongoKitten on Kitura and I got an error below when I tried to run it

`error: the library 'Application' requires macos 10.10, but depends on the product 'MongoKitten' which requires macos 10.14; consider changing the library 'Application' to require macos 10.14 or later, or the product 'MongoKitten' to require macos 10.10 or earlier.`

but my mac version is 10.15.5

**Comment by Joannis** [comment]
Hey @heart, make sure you've specified the minimum platform version in your Package.swift file as such:
https://github.com/OpenKitten/MongoKitten/blob/master/6.0/Package.swift#L8

**Comment by heart** [comment]
Thank you @Joannis it can solve my problem.

**Comment by Joannis** [comment]
You're welcome!
