### ISSUE TITLE
How to get MongoDB status

### ISSUE THREAD

**Issue by PanArtemG** [OpenKitten/MongoKitten#257]
Hello !!! 

Please tell me how can I get the MongoDB status by accessing it? Connected or not, only then I want to migrate.

Thanks!

**Comment by Joannis** [comment]
If you've got access to a `Cluster` object, you can access the `connectionState`.
https://github.com/OpenKitten/MongoKitten/blob/master/6.0/Sources/MongoClient/Cluster.swift#L45

**Comment by Joannis** [comment]
Connections have a `closeFuture` to see when it's not open anymore. But I highly recommend relying on `Cluster` unless you have a very specific usecase.

**Comment by PanArtemG** [comment]
<img width="998" alt="Снимок экрана 2021-02-02 в 18 12 59" src="https://user-images.githubusercontent.com/52529151/106628275-4a33e180-6582-11eb-8062-73896f4667f3.png">

Thanks for answering. I'm not quite clear how can I get it?

**Comment by Joannis** [comment]
Oh, this is in Fluent? The `MongoDatabase` has a `pool` which is a `MongoCluster`. The code is a bit ugly, but that's how you access that.
