### ISSUE TITLE
Can't run project with MongoKitten package

### ISSUE THREAD

**Issue by WCByrne** [OpenKitten/MongoKitten#26]
I'lll preface this with the fact that I'm still figuring out SPM. I'm trying to check MongoKitten but can't get it to run. A simple `print("test")` in main crashes with a BAD_ACCESS. 

Just curious if you have any insight if there is something in the lib that could be interfering. If I swap out MongoKitten for another package, update, and build; everything will run.

As for details I am using 1.3.0 and Swift Preview-2, also tried with older builds and the 6-20 snapshot.

Hope you can help get this sorted so I can see if it will work for me.

**Comment by Obbut** [comment]
I think we'll need a few more details.

- Are you using Xcode or building from the command line?
- What's your Package.swift?

**Comment by Joannis** [comment]
And what's the platform you're running on? macOS or Linux?

**Comment by WCByrne** [comment]
Hey guys, I'm on macOS 10.11.5. I can build both from command line and xCode but it crashes when I run. In Xcode i get the BAD_ACCESS on my `print("test")` line, from command line just `Segmentation fault 11`.

Package.swift just has MongoKitten, I've tried with various minor versions (and related swift versions)
`.Package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 1, minor: 3)`

**Comment by Obbut** [comment]
I see. We (me and @Joannis) are currently on 10.12 developer beta, but if you could share your project with us I'll setup a partition with El Capitan and try to reproduce and fix your problem. 

Thanks!

**Comment by WCByrne** [comment]
I have 10.12 on my laptop I will give that a try first.

I just started with a  fresh project in command line with just
- Package.swift
- Sources
   - main.swift (just a single line `print("test")`)

built that but running still give the fault, unless I remove the print("test")

I'll let you know what happens on 10.12

**Comment by WCByrne** [comment]
Yup, definitely a 10.11 issue. Works fine on 10.12
