### ISSUE TITLE
distinctValues function on MongoCollection does not use query

### ISSUE THREAD

**Issue by rgroult** [OpenKitten/MongoKitten#261]
**Describe the bug**
The query value parameter is not used on DistinctCommand initialiser

Inside this function:

`

extension MongoCollection {

    public func distinctValues(forKey key: String, where query: Document? = nil) -> EventLoopFuture<[Primitive]> {
        return pool.next(for: .basic).flatMap { connection in
            let command = DistinctCommand(onKey: key, inCollection: self.name)
            return connection.executeCodable(
                command,
                namespace: self.database.commandNamespace,
                in: self.transaction,
                sessionId: self.sessionId ?? connection.implicitSessionId
            )
        }.decodeReply(DistinctReply.self).map { $0.distinctValues }._mongoHop(to: hoppedEventLoop)
    }
}

`

**To Reproduce**
Try to execute a distinctValues request with a query

**Expected behavior**
The distinctValues should use provided query inside the DistinctCommand to filter results

**Server-side Swift:**
 - OS: macOs
 - Swift Version: 5.X
 - MongoKitten  Version 6.6.6 (the Devil version :D)

**Comment by Joannis** [comment]
Sorry, that's a terrible oversight! Thanks for the report, I'll fix it later this week. Since you're already into the code, I'm also happy accepting a PR.

**Comment by Joannis** [comment]
By the way, the internals of that API call can be used by your codebase to construct a properly formatted distinct call.

**Comment by Joannis** [comment]
Merged. Thanks!
