### ISSUE TITLE
The operation couldn’t be completed. (MongoKittenCore.InsertReply error 1.), but document is inserted

### ISSUE THREAD

**Issue by petershaw** [OpenKitten/MongoKitten#267]
Hi, 
I have a question that is similar, but not quite the one in: https://github.com/OpenKitten/MongoKitten/issues/147
I get the same error, but... after the first document took about 15s to import all other documents imported directly. But all imports have the message `The operation couldn’t be completed. (MongoKittenCore.InsertReply error 1.)` in `info.localizedDescription` where info is the response from ` result.whenSuccess `.

here is my import function: 
```
let loginEvent = try decoder.decode(LoginEvent.self, from: data)
result = collection.insertEncoded(loginEvent)
```

Here i get the error: 
```
result.whenSuccess { info in            
    dump(info)
    print(info.localizedDescription )
 }
```

The output looks like this: 
```
▿ MongoKittenCore.InsertReply
  - ok: 1
  - insertCount: 1
  - writeErrors: nil
  - writeConcernError: nil
The operation couldn’t be completed. (MongoKittenCore.InsertReply error 1.)
```

Where does the "error 1" is coming from? I would ignore it, if the first document would not smell so much.... 
My LoginEvent is a Codable and straight forward generated from openapi:
```
public struct LoginEvent: Codable {
    public var category: LoginCategory
    public var action: LoginEventActions
    public var uuid: UUID
    public var client: UUID
    public var user: UUID
    public var eventtime: Date

    public init(category: LoginCategory, action: LoginEventActions, uuid: UUID, client: UUID, user: UUID, eventtime: Date) {
        self.category = category
        self.action = action
        self.uuid = uuid
        self.client = client
        self.user = user
        self.eventtime = eventtime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case action
        case uuid
        case client
        case user
        case eventtime
    }

    // Encodable protocol methods
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(category, forKey: .category)
        try container.encode(action, forKey: .action)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(client, forKey: .client)
        try container.encode(user, forKey: .user)
        try container.encode(eventtime, forKey: .eventtime)
    }
}
```

The inserted document looks fine. The message in `info.localizedDescription` makes me nervous. Is there is something I can do better? 

tia.

**Comment by Joannis** [comment]
That's odd, because the only way I check whether the reply is an error (and therefore should be thrown) is by checking that `ok == 1`. If `ok != 1`, then it gets throws. And since you got a reply at all, that means every step before that (including networking & encoding) was successful.

**Comment by Joannis** [comment]
I can improve the Debug Description, I guess that's all.

**Comment by petershaw** [comment]
Thanks a lot @Joannis
