### ISSUE TITLE
Iterating over docs  - super slow

### ISSUE THREAD

**Issue by justmark** [OpenKitten/MongoKitten#34]
I'm using 1.4.1 of MongoKitten.  

I'm pulling back an entire collection (200 docs) and using Array() so that I preserve the cursor contents after iterating over them.  Each document has about 150 fields, most of which are integer and float values.  Some documents have embedded documents (max 5) that are versions of the main document.

Just iterating over the entire collection, and printing something simple like "doc found" runs incredibly fast.  As soon as I test each doc for a condition, I end up with the process taking an extremely long time.  Each iteration is taking about 5 seconds.  

This is super slow:

```
for doc in allDocs {
	if doc["enabled"].stringValue == "yes" {
		print("System \(doc["nickname"]) is enabled")
	}
}
```

This is almost instantaneous:

```
for doc in allDocs {
	print("doc found")
}
```

**Comment by Obbut** [comment]
Is this also slow when building on release? If so, could you provide some sample data with which you experience the issue so that we can profile it and see where the performance is going?

**Comment by justmark** [comment]
It wasn't the release version.  I'll try it immediately and get back to you.

**Comment by justmark** [comment]
In release mode things are much faster.  Its still not as fast as our Ruby/Mongoid version, but the entire process runs in about 8 seconds.

The enabled key is one of the latter fields in the collection.  

Thanks for the super fast response!

**Comment by Obbut** [comment]
Alright. I discussed with @Joannis and he is going to pick this up.

We haven't really used MongoKitten before with documents of this size, and that's currently not part of our testing, so we haven't noticed this problem before. Optimising our BSON performance is something we've been planning on doing on a short term, however, as we want to be just as fast other implementations.

**Comment by Joannis** [comment]
@justmark I've updated BSON to be more performant on larger Documents. Can you try to fetch the BSON dependency again? BSON 3.5.3 should fix a lot of your issues, so I'm really curious if this fixes your problems.

**Comment by justmark** [comment]
Sure, I'll give it a try this morning and get back to you shortly.

**Comment by justmark** [comment]
I need to rename this ticket to "insanely fast."

I tested both in release mode, and just standard build.  With the standard build there is a slight pause (fraction of a second) before results appear.  If I build for release, all the data appears instantly.  The changes you made are even faster than the results we got from our Go version!   

Thanks for the quick response on this.

**Comment by Joannis** [comment]
I'm glad it worked. Thanks for the feedback!
