### ISSUE TITLE
package dependency sock failing to build

### ISSUE THREAD

**Issue by baxtercr** [OpenKitten/MongoKitten#36]
vapour build fails when include mongokitten package.

.Package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 1, minor: 4)

ERROR
The dependency graph could not be satisfied (https://github.com/czechboy0/Socks.git

Running Vapor Toolbox v0.8.0
Swift DEVELOPMENT-SNAPSHOT-2016-08-18-a

**Comment by Obbut** [comment]
We'll release a new version of MongoKitten compatible with 08-18 later today or tomorrow. For now you can use the previous version of Vapor with 07-25-a.
