### ISSUE TITLE
CryptoSwift licence and acknowledgment

### ISSUE THREAD

**Issue by krzyzanowskim** [OpenKitten/MongoKitten#37]
Hi, according to this [License](https://github.com/krzyzanowskim/CryptoSwift/blob/master/LICENSE licence):
> If you use this software in a product, an acknowledgment in the product documentation is required"

do you mind add acknowledgment to README.md?
thanks.

**Comment by Obbut** [comment]
Whoops, sorry for that. We previously depended on a fork of CryptoSwift for cryptography but last week I included the code as a temporary to prevent a module name collision with some packages. In the rush to get the new version of MongoKitten out and compatible I totally forgot about this.

I have updated the readme.
