### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by marlon-sousa** [OpenKitten/MongoKitten#39]
Hello,

My name is Marlon.

I am a software developper, but I am not used to systems like GitHub.

I am interested in your project but couldn't find any other way to talk to you other than openning an issue.

If I should contact you by another way, please let me know.

I have tried to install the mongoKitten library on my Mac (late 2013, Macbook Air, mac OS 10.11.5, Xcode 7.3.1 ) but couldn't make it work.

I followed your documentation.

The requirements are:

• A MongoDB server : do I need to have a mongoDB server on my machine? Because I have an instance running somehwere else and was planning to use it. Any way I tried it with and without mongo installed and got the same results. - checked
• Some basic knowledge of MongoDB or time to research about MongoDB - checked
• The swift version described in  .swift-version , see 
swiftenv. - I did try innstalling mongoKitten with and without swiftenv installed. When I installed swiftEnv, I set it to swift 2.2 and also used the system version and got no results.-  Checked.

As I have xcode 7.3.1, I am assuming for me the install setup should be using swift 2.2. I then installed carthage and created a cartfile with 

github "OpenKitten/MongoKitten" ~> 1.1

Then I issued carthage update and carthage downloaded mongoKitten 1.5

But after downloading, nothing happened. The folder with sources was downloaded but the build folder is empty. Carthage pointed a xcodebuild log, but the file is empty.

No other logs, no errors on the terminal shown during carthage update, nothing else.

I am assuming either that there is some dependency that I happen not to have or that my system is lacking something but I have no idea about what it would be.

Can you help me?

**Comment by Joannis** [comment]
@marlon-sousa We don't currently support Swift 2.2 anymore with MongoKitten 1.5. If you prefer using carthage we'd recommend sticking to `MongoKitten 1.1` by using `github "OpenKitten/MongoKitten == 1.1.0`. Otherwise you can upgrade to the latest supported Swift 3 snapshot.

For Swift 3 you can install [swiftenv](https://swiftenv.fuller.li) to manage your snapshots. Enter the MongoKitten directory and run `swiftenv install`

**Comment by marlon-sousa** [comment]
Hello,

Thanks for the response.


I however am still having problems with installation. although not the original related problem.

Now, I got an error due to a file not found problem. Logs pasted below:

** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(1 failure)
<unknown>:0: error: no such file or directory: '/Users/marlon/Documents/aulaiOS/Organiza/Carthage/Checkouts/BSON/Sources/Compatibility.swift'
A shell task (/usr/bin/xcrun xcodebuild -project /Users/marlon/Documents/aulaiOS/Organiza/Carthage/Checkouts/BSON/Xcode/BSON.xcodeproj -scheme BSON OS X -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(1 failure)

Although I really do not see the file, I also do not know where it s supposed to come from 

exactly.

**Comment by Joannis** [comment]
@marlon-sousa I'm unsure if we'll be able to fix any issues with Carthage anymore since we dropped the support in favour of SPM. Is there any reason you're using Swift 2.2 instead of the soon to be released Swift 3.0? I think I'd be able to better assist you if you'd use a newer Swift version.

Are you working on a server project? Or a macOS/iPhone/iPad application?

**Comment by marlon-sousa** [comment]
An iphone app. As I understand it: Xcode 7.3 is only able to compile  Swift 2.2 . Ass Xcode eight is still beta the, I don't think I can use it for my project now. Are  binaries compatible? If they are, I can use Xcode eight to compiled the library and then use it in Xcode 7.3 in my project.
If there are ways to use swift tree in Xcode 7.3 I would be very happy smile. 

Obrigado,
Marlon Brandão de Sousa

**Comment by Joannis** [comment]
@marlon-sousa We're not compatible with Swift 2.2/2.3 and we're not supporting Xcode 7.3 anymore. The binaries aren't compatible but Xcode 8.0 and Swift 3.0 are really close to release.

**Comment by Obbut** [comment]
I'm closing this issue for now. The GM's of Xcode 8, macOS 10.12, iOS 10, tvOS 10 and watchOS 3 are out now so the final versions will be released very soon. The version of Swift included with the final release of Xcode 8 will be the version supported by MongoKitten and that would allow you to include it in apps on the app stores.

Feel free to open another issue if you encounter any other problems while using MongoKitten / BSON with Swift 3 or Xcode 8
