### ISSUE TITLE
A question about the `_id == .null`, 

### ISSUE THREAD

**Issue by lneoe** [OpenKitten/MongoKitten#44]
when create a new document, only the `_id == .noting` been handled  

``` swift
if input["_id"] == .nothing {
    var output = input
    output["_id"] = ~ObjectId()
    newDocuments.append(output)
    return .document(output)
```

question is the `_id == .null` should be covered, or just handle this in my own program?

**Comment by Obbut** [comment]
The _id can only really be null when explicitly set on the side of the api user, so why would we? Shouldn't really hurt either, though, since I don't think it's really valid to use null as an _id in mongodb. I'll discuss this in more detail with @Joannis later and come back to you.
