### ISSUE TITLE
Documents array doesnt use Array<AnyObject( or other)>

### ISSUE THREAD

**Issue by sezgin** [OpenKitten/MongoKitten#49]
when using Vapor framework that is best swift framework
query result [Document] that is array, but json engine cant convert this, it needs [AnyObject]. and Document object cant allow downcase [AnyObject].

I think Documents has return [AnyObject] option because for example i want to return all users list, i should loop in Object to convert Json engine valid type

<img width="305" alt="ekran resmi 2016-10-13 16 54 04" src="https://cloud.githubusercontent.com/assets/4388566/19351758/ae7c43bc-9165-11e6-8779-0ff14a7f0b7c.png">

**Comment by Joannis** [comment]
We have a JSON parser/serializer build into our Documents. It's not as battle tested as the rest of the JSON parsers/serialisers but has proven to work in all our conditions.

We don't currently support any other JSON formats except as a String. But you could map a BSON Document to SwiftyJSON, Vapor JSON and other objects manually or convert via String, however converting via strings wouldn't be very performant and makes use of ExtendedJSON.

I'm not entirely sure what you're trying to do in detail, so I can't really help you in detail.
