### ISSUE TITLE
Problem connecting to localhost

### ISSUE THREAD

**Issue by HaraKikiri** [OpenKitten/MongoKitten#50]
I can't seem to be able to figure this out ...
Every time I use the simple sample code connecting to localhost I get 

> "MongoDB is not available on the given host and port (Socket failed with code 61 ("No data available") [connectFailed] "Unknown error")."

There are no issues when I connect to mLab.
Why could this be? Mongo is running locally and if I connect in a second terminal with the 'mongo' command everything works fine. I connect to "mongodb://localhost", have tried adding the correct port too, but no luck!

**Comment by Joannis** [comment]
How are you creating the `Server` object?
`Server("mongodb://localhost")` should work `Server(hostname: "mongodb://localhost")` shouldn't.
MongoKitten 1.7 has some very unnatural initializers.
If this doesn't solve your problem, changing from `localhost` to `127.0.0.1` could

**Comment by HaraKikiri** [comment]
I used

> do {
>     self.server = try Server("mongodb://localhost", automatically: true)
> } catch {
>     print("MongoDB is not available on the given host and port (\(error)).")
> }

And changing from `localhost` to `127.0.0.1` actually worked. Thanks a lot for everything!
