### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by pkcs12** [OpenKitten/MongoKitten#51]
Package.swift

```
import PackageDescription

let package = Package(
    name: "daemon",
    dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1),
        .Package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 2)
    ],
    exclude: [
        "Config",
        "Database",
        "Localization",
        "Public",
        "Resources",
        "Tests",
    ]
)
```

I'm trying to build template project which vapor generates. The only change I'm doing is adding dependency to beta MongoKitten. With this dependency it fails to build on Ubuntu.
Compiler fails with the following error:

```
/whatever/daemon/Packages/CryptoKitten-0.0.0/Sources/Cryptography/SHA1/SHA1.swift:200:18: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
        hashCode = [
        ~~~~~~~~~^~~
```

Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-38-generic x86_64)
Vapor Toolbox v1.0.3
Swift version 3.0-dev (LLVM b9bd56d1b8, Clang 23f1b289cf, Swift edd2ecdf0c)
Target: x86_64-unknown-linux-gnu

**Comment by Joannis** [comment]
Thanks for the report! It seems like this is a CryptoKitten bug rather than a MongoKitten. Luckily we're the same developers 👍 

The compiler fails on your server/computer because it's probably at least a bit weaker than mine.

I've pushed an update to the affected package which might solve it. So please report back if it doesn't.

**Comment by pkcs12** [comment]
Now I see this:

```
/home/vlider/daemon/Packages/CryptoKitten-0.0.2/Sources/CryptoKitten/SHA1/SHA1.swift:182:18: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
        hashCode = [
        ~~~~~~~~~^~~
```

**Comment by Joannis** [comment]
If you remove the `Packages` folder, and specifically/especially `CryptoKitten-0.0.2` I hope that fixed it.

**Comment by Joannis** [comment]
Of course the official method is `swift build --clean dist`. Sorry 😁

**Comment by pkcs12** [comment]
I'm always doing `vapor clean`, or `sudo vapor clean` before building it again, just to be sure that dependencies will be fetched correctly.
I just noticed that the same code compiles without any problem on macOS. From today I see different compile errors on my Ubuntu:

```
/whatever/daemon/Packages/BSON-3.8.0/Sources/ValueConvertible.swift:89:11: error: use of undeclared type 'RegularExpression'
extension RegularExpression : ValueConvertible {
          ^~~~~~~~~~~~~~~~~
/whatever/daemon/Packages/BSON-3.8.0/Sources/ValueConvertible.swift:89:11: error: use of undeclared type 'RegularExpression'
extension RegularExpression : ValueConvertible {
          ^~~~~~~~~~~~~~~~~
/whatever/daemon/Packages/BSON-3.8.0/Sources/ValueConvertible.swift:89:11: error: use of undeclared type 'RegularExpression'
extension RegularExpression : ValueConvertible {
          ^~~~~~~~~~~~~~~~~
/whatever/daemon/Packages/BSON-3.8.0/Sources/ValueConvertible.swift:89:11: error: use of undeclared type 'RegularExpression'
extension RegularExpression : ValueConvertible {
          ^~~~~~~~~~~~~~~~~
/whatever/daemon/Packages/BSON-3.8.0/Sources/ValueConvertible.swift:89:11: error: use of undeclared type 'RegularExpression'
extension RegularExpression : ValueConvertible {
          ^~~~~~~~~~~~~~~~~
/whatever/daemon/Packages/BSON-3.8.0/Sources/ValueConvertible.swift:89:11: error: use of undeclared type 'RegularExpression'
extension RegularExpression : ValueConvertible {
          ^~~~~~~~~~~~~~~~~
/whatever/daemon/Packages/BSON-3.8.0/Sources/ValueConvertible.swift:89:11: error: use of undeclared type 'RegularExpression'
extension RegularExpression : ValueConvertible {
          ^~~~~~~~~~~~~~~~~
/whatever/daemon/Packages/BSON-3.8.0/Sources/ValueConvertible.swift:89:11: error: use of undeclared type 'RegularExpression'
extension RegularExpression : ValueConvertible {
          ^~~~~~~~~~~~~~~~~
```

Now something missed in BSON. But again - same code compiles on macOS

**Comment by Joannis** [comment]
@pkcs12 which swift version are you running?

**Comment by Joannis** [comment]
I can't replicate this issue on Swift 3.0

**Comment by pkcs12** [comment]
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-38-generic x86_64)
Vapor Toolbox v1.0.3
Swift version 3.0-dev (LLVM b9bd56d1b8, Clang 23f1b289cf, Swift edd2ecdf0c)
Target: x86_64-unknown-linux-gnu

**Comment by pkcs12** [comment]
I tried to use non-beta release and there is another error now in GridFS.swift:

```
/whatever/daemon/Packages/MongoKitten-1.7.1/Sources/MongoKitten/GridFS.swift:161:41: error: cannot convert value of type 'Int64' to expected dictionary value type 'Value'
                                   "n": ~Int64(n),
                                        ^~~~~~~~~
                                        Value(   )
```

My Package.swift file:

```
import PackageDescription

let package = Package(
    name: "daemon",
    dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1),
        .Package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 1)
    ],
    exclude: [
        "Config",
        "Database",
        "Localization",
        "Public",
        "Resources",
        "Tests",
    ]
)
```

Guys, please suggest something

**Comment by Joannis** [comment]
@pkcs12 I've tried everything to reproduce it. I've ran this on Swift 3.0 on both Linux (Ubuntu 15.10 and 16.04) as well as macOS Sierra. Due to [financial problems and a lack of time(https://github.com/OpenKitten/MongoKitten/wiki/Project-status) I can't commit a lot of effort into MongoKitten at the moment. The only things I can suggest are cleaning your dependency folder and updating to MongoKitten 2.

But I can't find the cause of this error at all.

**Comment by Joannis** [comment]
@pkcs12 I think I see what's going on. You're running a version of swift that's in beta. Due to this the compiler can't parse that line of code correctly throwing an error. If you switch to the latest release version of Swift 3.0 you should be fine.

**Comment by pkcs12** [comment]
Ok, could somebody please tell me how to install non-development version of swift 3.0 on Ubuntu 16.04.1?
I tried with swiftest, and manually - but there are only 2.x and 3.0-dev, there is no 3.0 release. Maybe it's only available for macOS?

**Comment by Joannis** [comment]
Shouldn't the [september 13](https://swift.org/download/#releases) release work?
I ran that with no compilation problems.
Otherwise you might be able to use swiftenv to install `3.0-RELEASE` and default to that using `swiftenv global 3.0-RELEASE`

**Comment by pkcs12** [comment]
I only see release for Ubuntu 14 and 15, but not for 16
```
swiftenv install 3.0-RELEASE
We don't have build instructions for 3.0-RELEASE.
```

**Comment by Joannis** [comment]
@pkcs12 We found a bug just now with an operator being ambiguous and swift not always finding the relevant one. Not sure when it's affecting users but we made sense of why. So if you fetch the latest version it *should* be fixed.

**Comment by pkcs12** [comment]
now this error:
```
/whatever/daemon/Packages/BSON-3.8.3/Sources/ValueConvertible.swift:89:11: error: use of undeclared type 'RegularExpression'
extension RegularExpression : ValueConvertible {
          ^~~~~~~~~~~~~~~~~
```

Dependencies in Package.swift:

```
.Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 1),
.Package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 2, minor: 0)
```

**Comment by Joannis** [comment]
What OS are you compiling at? This issue should only rise at operating systems that aren't Linux, iOS and macOS.

**Comment by pkcs12** [comment]
I posted this information earlier: Ubuntu 16.04.1

**Comment by Joannis** [comment]
Oops. Sorry! I'm getting confused a bit! Swift 3.0.1 does have a 16.04 release and 3.0.0 can be ran by installing the ubuntu 15.10 release.

**Comment by pkcs12** [comment]
FANTASTIC!
I just installed swift-3.0.1 on my Ubuntu 16.04, and now it compiles! Thanks you!

**Comment by Joannis** [comment]
Cool! Let me know if you have anything else! :)
