### ISSUE TITLE
Compile Error on Download + Clean Build with Xcode 8.1

### ISSUE THREAD

**Issue by wpccolorblind** [OpenKitten/MongoKitten#55]
1. With Xcode 8.1
2. Download latest master
3. Build MongoKitten

Expected - 
Builds.

Actual -
Two compiler errors (see attached).  

Error text:  <path>/MongoKitten-master 2/Sources/MongoKitten/Cursor.swift:70:32: Cannot convert value of type 'Int64' to expected dictionary value type 'Value'

![screen shot 2016-10-25 at 11 29 08 pm](https://cloud.githubusercontent.com/assets/735111/19715568/f6d43e90-9b0a-11e6-997f-75b00a74d0c5.png)

**Comment by JustinM1** [comment]
I had that issue in another spot on another version of xcode but it appears to be happening in other spots as well, it seems to be a compile bug. In this case, change it to Value.int64(self.cursorID) or .int64(self.cursorID). The ~ is supposed to tell compiler it is a Value type but its not picking it up in certain situations. Make sure to remove ~ when you change it to .int64.

**Comment by Joannis** [comment]
@wpccolorblind we ( @JustinM1 and I ) found the solution. Working on it!

**Comment by Joannis** [comment]
Latest release should've fixed your problem

**Comment by wpccolorblind** [comment]
Confirmed fix with latest release.  Works great, you guys are amazing!

**Comment by Joannis** [comment]
I'm closing the issue since it's fixed. Feel free to open this/another issue when you have a question/problem.
