### ISSUE TITLE
Cannot use MongoKitten with Vapor HTTP

### ISSUE THREAD

**Issue by darkermatter** [OpenKitten/MongoKitten#56]
I'm new to Swift and I'm probably missing something. I can't compile after importing MK and Vapor HTTP as there is a clash with Server:
```
main.swift:5:13: reference to generic type 'Server' requires arguments in <...>

let server: Server!
            ^


** BUILD FAILED **
```
Is there a way of importing MK into a namespace?

**Comment by Joannis** [comment]
You could use `MongoKitten.Server`

**Comment by darkermatter** [comment]
Wow @Joannis - thanks!

I didn't even have time to take a swig of my coffee!

Closing.
