### ISSUE TITLE
Argument labels '(_:, automatically:)' do not match any available overloads

### ISSUE THREAD

**Issue by philcms1** [OpenKitten/MongoKitten#57]
Hi, following the tutorial:

`
dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 1),
        .Package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 2, minor: 0)
    ]`

Code:

`
import MongoKitten
let server: Server
server = try Server("mongodb://localhost:27017", automatically: true)
`

I am getting this error when building:

`Compile Swift Module 'App' (3 sources)
/Foo/Sources/App/main.swift:9:18: error: argument labels '(_:, automatically:)' do not match any available overloads
    server = try Server("mongodb://localhost:27017", automatically: true)
                 ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Foo/Sources/App/main.swift:9:18: note: overloads for 'Server' exist with these partially matching parameter lists: (mongoURL: NSURL, using: MongoTCP.Type, automatically: Bool, maxConnecti
ons: Int), (mongoURL: String, using: MongoTCP.Type, automatically: Bool, maxConnections: Int), (hostname: String, port: UInt16, authenticatedAs: (username: String, password: String, against: String)?, runningTcpDriver: MongoTCP
.Type, automatically: Bool, maxConnections: Int)
    server = try Server("mongodb://localhost:27017", automatically: true)`

Providing expected parameters is working of course:

`server = try Server(mongoURL: "mongodb://localhost:27017", using: Socks.TCPClient.self, automatically: true, maxConnections: 5)`

**Comment by Joannis** [comment]
`let server: Server server = try Server(mongoURL: "mongodb://localhost:27017", automatically: true)`

The `mongoURL:` is required

**Comment by philcms1** [comment]
Thanks! I didn't even see that... I should just take the plunge and do a PR for the documentation...
