### ISSUE TITLE
Server initializer does not decode percent characters from mongodb:// url

### ISSUE THREAD

**Issue by sebastienwindal** [OpenKitten/MongoKitten#59]
I tried to pass a mongodb:// url with a password that contains an @ symbol like this one:

```
mongodb://joeshmo:password%40@127.0.0.1:27017
```

the server init is not decoding percent characted when extracting user and password from url

``` swift
public convenience init(_ url: NSURL, using tcpDriver: MongoTCP.Type = Socks.TCPClient.self, automatically connecting: Bool = true) throws
```

Using `removingPercentEncoding`  fixed my issue:

``` swift
 if let user = url.user?.removingPercentEncoding, let pass = url.password?.removingPercentEncoding
```

**Comment by Joannis** [comment]
The latest MongoKitten 2 version has this implemented now. Feel free to close the issue if it's working for you :)
