### ISSUE TITLE
Dash documentation link broken

### ISSUE THREAD

**Issue by owenworley** [OpenKitten/MongoKitten#61]
There is an `Install in Dash` button on this site:
http://openkitten.github.io/MongoKitten/docs/

The link currently points to: http://planteam.github.io/MongoKitten/MongoKitten.xml which 404s.

It looks like this link should actually be: http://openkitten.github.io/MongoKitten/MongoKitten.xml

However, the contents of the above .xml file also points to: http://planteam.github.io/MongoKitten/docs/docsets/MongoKitten.tgz

Which also 404s, and should point to:  http://openkitten.github.io/MongoKitten/docs/docsets/MongoKitten.tgz

**Comment by Joannis** [comment]
Sorry about that! The planteam link is the old organisation this project was in. And I've been having problems with generating the docs lately.

I'll check again right now if I can get our generation up and running

**Comment by owenworley** [comment]
No probs, I would have pr'd if I could :)

**Comment by Joannis** [comment]
@owenworley I fixed the page.. finally. But the docs URL should work now

**Comment by owenworley** [comment]
Awesome, thank you :)
