### ISSUE TITLE
BSON Module

### ISSUE THREAD

**Issue by sebasjuan94** [OpenKitten/MongoKitten#62]
Hey guys,

I have added all of your files manually into my project and everything seems to be working fine until I try running the project and the compiler chokes because it says it cannot find the "BSON" module.
What can I do to fix this problem?

Thanks!

**Comment by Joannis** [comment]
MongoKitten has a few dependencies that we link together using SPM. I think the best option would be to use SPM for creating an xcodeproj that you can depend on. But I don't know how that would work exactly. What kind of project are you creating?

**Comment by sebasjuan94** [comment]
Yea I can't see how that would work either. The first problem is that it seems like no matter what I do I can't get any imports at all. Not even using the SPM. I did the following commands...

$ mkdir SwiftProject
$ cd SwiftProject
$ swift package init --type executable
$ swift package generate-xcodeproj

With the package.swift looking like so:

import PackageDescription
let package = Package(
    name: "SwiftProject",
    dependencies: [
        .Package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 2, minor: 0)
    ]
)

When I open the Xcode project and I go to main.swift and try to import BSON or even MongoKitten, the compiler can't seem to find them anywhere...I even tried adding them as required dependencies under linked frameworks and libraries under the general section of my project. Note that even though the compiler can't seem to find the frameworks, I can see them under my products folder and I also have all the files under my Sources folder.

The other issue is that I am creating an IOS app in which I am using cocoa pods to compile third-party libraries. So again, I don't know how I could merge the two projects? :?
Another thing is that I have this application on the app store already and in order for any update to get approved I have to conform to the new protocol Apple has regarding ipv6 addresses...So I was wondering if I even make this work somehow to merge the MongoKitten library into my project if it would be able to conform to this protocols....I am sorry for such a long response, I hope you can shine some light on this.

Thanks a ton!

**Comment by Joannis** [comment]
I personally never tested IPv6 but the library we use for that will definitely be able to make it work.

As to why you're unable to import MongoKitten I'm unsure. I've been trying to replicate your commands for the same result but it works for me.

Which Xcode version do you run?
