### ISSUE TITLE
~ operator causes slow builds

### ISSUE THREAD

**Issue by darkermatter** [OpenKitten/MongoKitten#63]
Hi!

Creating a document using the ```~``` operator really slows builds. I recommend using ```.string(variable)```, etc.

As an example, I had a 16 element document which took 30 seconds to build on my machine. After changing all the ```~``` operators to .string() and .boolean() the build time was almost instantaneous (It almost felt like I was using Go again).

I guess it has something to do with the famous type inference problem (I'm even using Xcode 8.1) which sees massive increases in build time.

For now, I recommend that you discourage the use of the operator in the documentation.

**Comment by Joannis** [comment]
I'm working on BSON 4 where we don't use the Value enum notation anymore and replaced it with a direct dictionary.

So your code would look like this:

```swift
let fullName = "Joannis Orlandos"

struct MyType: ValueConvertible {
  func makeBsonValue() -> BSON.Value {
    return BSON.Value.document([
        "thing": 3.14
      ])
  }
}

let document = [
  "string": "literal",
  "bool": true,
  "name": fullName,
  "embedded": [
    "document": true
  ] as Document,
  "otherEmbeddedType": MyType()
] as Document
```

**Comment by darkermatter** [comment]
nice! 😀

**Comment by Joannis** [comment]
@darkermatter `.Package(url: "https://github.com/OpenKitten/MongoKitten.git", "3.0.0-alpha")` if you want to mess with it.
