### ISSUE TITLE
Compilation fails on BSON module

### ISSUE THREAD

**Issue by pkcs12** [OpenKitten/MongoKitten#64]
> Ubuntu 16.04.1
> Swift version 3.0.1 (swift-3.0.1-RELEASE)
> Target: x86_64-unknown-linux-gnu
> OpenSSL 1.0.2g  1 Mar 2016
> curl 7.52.0-DEV (x86_64-pc-linux-gnu) libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
> Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

Same code compiles on macOS, but on Ubuntu errors out:
```
/whatever/project/Packages/BSON-0.0.44/Sources/ExtendedJSON.swift:447:36: error: argument labels '(subtype:, data:)' do not match any available overloads
                            return Binary(subtype: subtype, data: byteBuffer)
                                   ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/whatever/project/Packages/BSON-0.0.44/Sources/ExtendedJSON.swift:447:36: note: overloads for 'Binary' exist with these partially matching parameter lists: (data: Data, withSubtype: Binary.Subtype), (data: [UInt8], withSubtype: Binary.Subtype)
                            return Binary(subtype: subtype, data: byteBuffer)
                                   ^
```

**Comment by Joannis** [comment]
@pkcs12 It should be fixed in the latest update.

**Comment by vlider** [comment]
Thanks, everything is fine after I clean built.
