### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by swiftymarks** [OpenKitten/MongoKitten#66]
Hello, from some reason when ever I build using the swift package manager I always endup having this kind of error,

I am using this version
 .Package(url: "https://github.com/OpenKitten/MongoKitten.git", "3.0.0-alpha")

error: The dependency graph could not be satisfied because an update to `https://github.com/OpenKitten/BSON.git' is required

**Comment by Joannis** [comment]
`swift package update` will update your packages like BSON.

Alternatively `swift package --clean dist` will clean up your packages folder after which you can create an Xcodeproject with `swift pacakge generate-xcodeproj` or `swift build` to build it using the terminal.

Swift still has BSON in it's cache from a previous MongoKitten version (1.7 or 2.x) so you'll have to get the newer vesion.

**Comment by swiftymarks** [comment]
Thanks!
