### ISSUE TITLE
not able to build MongoKitten on ubuntu 16.04 64 bit

### ISSUE THREAD

**Issue by surendratiwari3** [OpenKitten/MongoKitten#73]
root@ubuntu:/usr/local/src/MongoKitten# swift build
Cloning https://github.com/OpenKitten/BSON.git
HEAD is now at 581a893 Reworked the entire API
Resolved version: 0.0.44
Cloning https://github.com/OpenKitten/CryptoKitten.git
HEAD is now at f61017a Merge pull request #1 from DevAndArtist/master
Resolved version: 0.0.2
Cloning https://github.com/vapor/socks.git
HEAD is now at bd9af15 Merge pull request #90 from vapor/fix-portableerrors
Resolved version: 1.2.0
Compile Swift Module 'SocksCore' (15 sources)
Compile Swift Module 'CryptoKitten' (14 sources)
Compile Swift Module 'BSON' (21 sources)
/usr/local/src/MongoKitten/Packages/BSON-0.0.44/Sources/ExtendedJSON.swift:447:36: error: argument labels '(subtype:, data:)' do not match any available overloads
                            return Binary(subtype: subtype, data: byteBuffer)
                                   ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/src/MongoKitten/Packages/BSON-0.0.44/Sources/ExtendedJSON.swift:447:36: note: overloads for 'Binary' exist with these partially matching parameter lists: (data: Data, withSubtype: Binary.Subtype), (data: [UInt8], withSubtype: Binary.Subtype)
                            return Binary(subtype: subtype, data: byteBuffer)
                                   ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /usr/local/src/swift-3.0.1-RELEASE-ubuntu16.04/usr/bin/swift-build-tool -f /usr/local/src/MongoKitten/.build/debug.yaml

**Comment by Joannis** [comment]
Ah.. it seems you're running the MonogKitten beta/alpha. Is this correct? The fix is about to be tagged as `"3.0.0-alpha7"`
