### ISSUE TITLE
Document bug with similar keys

### ISSUE THREAD

**Issue by sujaykakkad** [OpenKitten/MongoKitten#74]
Ok I found the bug. It is not related with the key "balance". There is some name conflict and it also changes the value inside another key.
eg
```swift
var mydoc: Document = ["balance_status": "Pending"] 
mydoc["balance"] = 50 //If I use the starting part of any key of mydoc it will happen. This will also happen if I use mydoc["balance_"] 
print("\(mydoc)") //This prints {"balance_status":{"$numberLong":"50"}}
print("\(mydoc['balance'])") //This prints int64(50)
try collection.insert(mydoc) 
```

When I do this "balance" key is not added in document but "balance_status" is changed to 50. So it is altering my document and also not adding my key. Please try to fix this.

**Comment by Joannis** [comment]
I've pushed the update for BSON

**Comment by sujaykakkad** [comment]
So is it fixed in new version?

**Comment by sujaykakkad** [comment]
Also tell me how can I get a deleted document on findAndModify with remove and new.
Similar to this
https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/

**Comment by Joannis** [comment]
I fixed it, yes. `collection.findAndModify` is the method you're looking for.

**Comment by sujaykakkad** [comment]
Ok I need a suggestion I have implemented two files for my API one is controller which handles routes and http responses and other is model which handles DB calls. So for schema validation using mainecoon where should I implement the mainecoon schema inside my controller or inside my model and also where should the validation be implemented?

**Comment by sujaykakkad** [comment]
I have referred to this repo which uses mongokitten.
https://github.com/IBM-Swift/TodoList-MongoDB/tree/master/Sources

**Comment by Joannis** [comment]
The schema should be created and registered to a model only once before exposing/using the model. So that'd probably be `main.swift`. The validation of the schema will be done every time the model is instantiated and will throw an error otherwise.
