### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by gormster** [OpenKitten/MongoKitten#75]
There seems to be no documentation for this library whatsoever.

How can this be? There's a tiny amount of autogenerated docs on http://mongokitten.openkitten.org, but it doesn't cover the Query Builder *at all*. Am I missing something here?

**Comment by Joannis** [comment]
http://mongokitten.openkitten.org is the generated API docs. Which doesn't contain use cases like how you'd use the Query builder.

I'm currently in the process of migrating tutorials and examples to [here](https://github.com/OpenKitten/Documentation) but it still requires manual navigation through the tree. This should become a proper website, but I'd need some assistance building the website so the UI and UX aren't horrible.

**Comment by Joannis** [comment]
https://github.com/OpenKitten/Documentation/blob/master/MongoKitten/Tutorials/QueryBuilder.md

**Comment by Joannis** [comment]
We've moved all information [here](http://docs.openkitten.org) now. If anything is missing that you need more information on, please tell us :)

**Comment by dylankbuckley** [comment]
It would appear the documentation is broken ...

**Comment by Joannis** [comment]
What is broken about it? There is some information missing here and there, but the basics should be covered and available at that URL.

**Comment by lgaches** [comment]
@dylankbuckley I've updated the generated documentation [here](http://docs.openkitten.org/). Some page was broken.
