### ISSUE TITLE
Reconnect after MongoDB Restarted 

### ISSUE THREAD

**Issue by surendratiwari3** [OpenKitten/MongoKitten#78]
i have created a process running continuously but it stuck when i restarted the mongodb server.so please provide a way to reconnect when mongoserver is up.

**Comment by sujaykakkad** [comment]
Even I am having the same issue. Please implement it in the next version. Also after implementation please provide a good documentation to gracefully handle connection issues like reconnection and reconnection timeout.

**Comment by surendratiwari3** [comment]
issue is solve..

**Comment by HiroshiHorie** [comment]
I'm having the same issue... please tell me how you solved this ?
It's unbelievable that there are no re-connecting methods....
