### ISSUE TITLE
Aggregation: Lookup doesn't work for array fields

### ISSUE THREAD

**Issue by mollywoodnini** [OpenKitten/MongoKitten#80]
Hi there,

Version: MongoKitten 3.0

I am trying to do a lookup regarding this docs: https://docs.mongodb.com/v3.2/reference/operator/aggregation/lookup/

The lookup aggregation in MongoKitten 3 works great when localField and foreignField are single elements. But it doesn't work for array elements.

In the following example the localField 'specs' is an array element:
```
let unwind = AggregationPipeline.Stage.unwind(atPath: "specs")
let lookup = AggregationPipeline.Stage.lookup(fromCollection: inventoryCollection, localField: "specs", foreignField: "size", as: "inventory_docs")
let pipe = AggregationPipeline(arrayLiteral: unwind, lookup)

let document = try inventoryCollection.aggregate(pipeline: pipe).makeDocument()
```
After the aggregation the document field "inventory_docs" is just an empty array.

Am I doing something wrong or is this a bug? Thanks.

Cheers,
Nini

**Comment by lgaches** [comment]
Try with the following

`
        let unwind = AggregationPipeline.Stage.unwind(atPath: "$specs")
        let lookup = AggregationPipeline.Stage.lookup(fromCollection: inventory, localField: "specs", foreignField: "size", as: "inventory_docs")
        let match = AggregationPipeline.Stage.matching(["inventory_docs": ["$ne":[] as Document] as Document] as Document)
        let pipe = AggregationPipeline(arrayLiteral: unwind, lookup)
`

**Comment by lgaches** [comment]
Just added a test
https://github.com/OpenKitten/MongoKitten/commit/9920505f555e4a6ef66d0c875516f7072f5edbbd

**Comment by Joannis** [comment]
We'll need to document the usage of Document better.

**Comment by mollywoodnini** [comment]
Thank you @lgaches, it works flawlessly.
