### ISSUE TITLE
[PROPOSAL] Database middlewares

### ISSUE THREAD

**Issue by Joannis** [OpenKitten/MongoKitten#82]
**Feature:** Database middlewares

This feature proposal is placed publicly on GitHub to discuss the future direction of MongoKitten more openly. This proposal specifically is aimed at adding a feature not commonly implemented in database drivers, namely the implementation of a database middleware system.

## Motivation

MongoKitten users generally use MongoKitten behind a web server like Vapor, Kitura, Perfect or Zewo. A lot of the time information is being passed from the router, through the middlewares, to the route until it reaches the database and then back. In this process there are a few tasks that the developer needs to be constantly aware of. Authentication and authorisation are a few important ones there.

Currently the authentication part can be handled in the WebFramework Middlewares where a cookie/header would validate the authentication status. The authorisation, or, the permissions to run a CRUD operation on a certain group of users, however, is something the developer has to implement.

This proposal would change primarily the way you interact with data from an API point of view with regards to authorisation.

## Proposed solution

The solution I propose is a Database middleware. This would enable the API user to define all security oriented code inside the middleware shrinking the amount of code that could contain a security bug.

In this middleware a Request would be received as well as a Context object. This Request would (in the initial implemenentation) be either a request for the operation `insert`, `find`, `update` or `delete` with the provided metadata. The Context object can be defined by the developer. This can be a user context containing authentication and permissions/authorization data.

The middleware can throw an error to prevent this request from executing. Useful when preventing a user from acting outside his/her permission/authorisation level.

The next option a middleware has is mutating the request. You can add extra requirements to the query. Int he case of a single API being accessed by multiple organisations whose data should not be mixed this can include adding the requirement of the organisation's identifier in the Document matching that of the organisation that the user belongs to.

Then, if the Request is accepted, the middleware executes the provided requests and receives either an error for any (connectivity) failure or a `Response` object. A `Response` has a `Cursor<Document>` that can be mutated, for example, to redact confedential information from a user without the authorisation to see said specified fields.

The result is clean interaction between the developer's code and MongoKitten.

## Code snippets

These snippets are made to look like Vapor, which I'm most familiar with. They're pseudocode and are not expected to work.

```swift
let db: MongoKitten.Database
let drop: Droplet

db.middleware = { request, context in
    guard let userContext = context as? Turnstile.Subject else {
      throw MyError.unauthenticated
    }
  
  if var matching = request.matching {
    matching["organisation"] = userContext.organisationId
    request.matching = matching
  }

  // Do not mutate the response
  return try request.execute()
}

// Fetches all users and returns it over the API
drop.get("users") { request in
  // The turnstile subject should in Vapor contain the authentication and authorisation details about the user.
  let cursor = try db["users"].find(matching: "age" > 25, inContext: request.turnstileSubject)

  // Make an array of this cursor
  let documents = Array(cursor)

  // Converts this result to extendedJSON
  return documents.makeDocument().makeExtendedJSON()
}
```

## Impact

The impact on existing API would be the addition of optionally passing a context to the supported operations. On collection/database/server level, a variable of the type `((Request, AnyObject) throws->(Cursor<Document>))` would be added for handling the middleware system. Where AnyObject is the passed context used for authorisation.

## Alternatives considered

This could be implemented in a library depending on MongoKitten, separate from MongoKitten. This would, however, prevent this functionality from applying at a global scale, hence making your application prone to security bugs regardless.

**Comment by justmark** [comment]
If a user were to sign in successfully to  a web application, and the user object had associated permissions with it, how would you see this being handled within the view?  

As an example, if there was a delete action on a row in a table, you wouldn't want to present the delete action to users who didn't have sufficient permission.  This means that the user object and testing of the permission needs to be accessible from Leaf, Mustache, Stencil, etc.

ie:

#if(currentUserCanDelete) {
<button>...</button>
}

I wouldn't want to be in a situation where all options were presented to a user, and only tested for authorization when the action was submitted to the database.

**Comment by Joannis** [comment]
If you manage to send a delete request to the server via a form or JSON API it'll be aborted by the middleware since the middleware would contain this critical logic. The template would have to process this separately using the same method the MongoKitten middleware does. However, authorisation would be a feature build on top of this proposal. So this proposal doesn't cover the integration between authorisation using Turnstile and MongoKitten the middleware but would enable a library to implement this relatively easily and securely.

A library build on top of Vapor and MongoKitten for integration could (or in my opinion _should_) provide easy integrations on top of the two libraries to prevent a delete action button from appearing.

**Comment by mark-crawford** [comment]
Question:  Would this proposed database middleware include adoption of an X.509 authentication/authorization implementation?  If not, are there any plans to implement the X.509 authentication/authorization model in the near future?

**Comment by Joannis** [comment]
The proposed middlewares would not implement X.509, that's separate. I do not have any plans to support X.509 currently. I'll be working on releasing MongoKitten 4 and Meow first. So X.509 is probably at least another 2-4 weeks down the road.

**Comment by Danulf** [comment]
This sounds like back-end-as-a-service such as FireBase, Parse, Meteor, et cetera.  In short, what are you thinking that isn't available from these other services?  What is better, how is your approach different?

(I assume you are considering this as something totally separate from the driver.)

**Comment by Joannis** [comment]
The idea we had within the team was to allow for a hook/middleware system that allows you to influence the processes in MongoKitten. It could be used for measuring statistics, aborting delete operations based on metadata like the user that's executing it or modifying the query to ensure someone only applies the operation to the entities it has access to.
