### ISSUE TITLE
Unable to use mongokitten with vapor

### ISSUE THREAD

**Issue by jazeelkt** [OpenKitten/MongoKitten#83]
I was trying to use MongoKitten in my vapor project:
.Package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 3)

On running `vapor xcode` I can see a folder for mongokitten in Packages folder, but it seems the generated xcode project is unable to locate the source files for MongoKitten. Also I notice that in Packages folder, the entry for mongokitten is like mongokitten.git whereas for all other modules it is like module-version. When I tried `swift package fetch` with just MongoKitten as dependency I am getting the following output:
`Cloning https://github.com/OpenKitten/MongoKitten.git
Illegal instruction: 4`

I am running Swift 3 on Xcode 8.

**Comment by lgaches** [comment]
You can find a simple example [here](https://github.com/lgaches/vapor-mongokitten_sample) using vapor and Mongokitten.

Do you have some code to share ?

**Comment by jazzmac93** [comment]
I tried on the vapor template for new project itself. There was no other dependency in the Package.swift file, except for vapor and mongokitten. I also tried the example provided. Running `vapor xcode` command does not generate a xcode project file. I can see the dependencies downloaded to Package folder, but I think there is some issue there. Without MongoKitten dependency the packages come in folders with name like Vapor-1.3.0, but with MongoKitten it is vapor.git. Could this be the reason for xcode file not being generated?

**Comment by Joannis** [comment]
The illegal instruction is triggered, for some reason. This results in the `.git` folders not being renamed.

Could you try running `swift package generate-xcodeproj`? `vapor xcode` wraps around that function but might add some other stages as well.

**Comment by jazzmac93** [comment]
Tried that too. Same output. On running `swift build` command, this is the output I got:
`Cloning https://github.com/vapor/mongo-provider.git`
`HEAD is now at 55b961b Merge pull request #3 from honghaoz/master`
`Resolved version: 1.1.0`
`Cloning https://github.com/vapor/mongo-driver.git`
`HEAD is now at e26a3f1 Merge pull request #30 from vapor/fluent-1.3`
`Resolved version: 1.0.9`
`Cloning https://github.com/OpenKitten/MongoKitten.git`
`Illegal instruction: 4`

Running `swift package --version` gives me this:
`Apple Swift Package Manager - Swift 3.0.0 (swiftpm-19)`

**Comment by Joannis** [comment]
I don't know why it would matter, but could you try updating to Swift 3.0.1 or 3.0.2? An error like that seems to me like a bug in SPM which is part of Swift. Updating may solve that.

**Comment by jazeelkt** [comment]
Downloaded Swift 3.0.2 toolchain and used it to fetch dependencies. That seemed to have fixed the issue. As you mentioned, could be something wrong with SPM.
Thanks for your support.
