### ISSUE TITLE
Cannot convert value of type 'CVaListPointer' to expected argument type '__darwin_va_list!'

### ISSUE THREAD

**Issue by ksigWyatt** [OpenKitten/MongoKitten#93]
Is it possible that `CVaListPointer` doesn't exist in the iOS native libraries for `Swift 3`? I'm not sure because it works on the sumulator... so it must.

Anyways, I have compiled my project for the simulator (using iOS 10.2) and it works fine, just a few warnings here and there but it builds. When I transition to an actual device running `iOS 10.2.1` the compiler complains saying:

> Cannot convert value of type 'CVaListPointer' to expected argument type '__darwin_va_list!'

As a result of this error (I believe) the imports that I use for the MongoKitten library aren't able to be made. In the code below - which is taken from the LogKitten-0.3.0/Sources/SyslogDestination.swift file. Perhaps I imported something incorrectly?

    #if os(Linux)
    import Glibc
    #else
    import Darwin
    #endif

    public final class SyslogDestination : PlaintextDestination {
        public override func log(_ message: String) {
            message.withCString { message in
                withVaList([message]) {
                    vsyslog(0, "%s", $0) //error here when using physical device on iOS 10.2.1 (Build 14D15)
                }
            }
        }
    }

**Comment by lgaches** [comment]
First of all MongoKitten is not designed to be used on iOS devices but server side. 

You can try to modify the code in this way :

```swift
#if os(Linux)
    import Glibc
#else
    import Darwin
#endif

public final class SyslogDestination : PlaintextDestination {
    public override func log(_ message: String) {
        message.withCString { message in
            withVaList([message]) {
                #if os(Linux) || os(macOS)
                vsyslog(0, "%s", $0)
                #endif
            }
        }
    }
}

```

**Comment by Joannis** [comment]
We could change this ourselves, for the rare occasion you'd need MongoKitten in the app.
I'd recommend this then:

```swift
#if !os(iOS)
  message.withCString { message in
    withVaList([message]) {
      vsyslog(0, "%s", $0)
    }
 }
#endif
```

**Comment by ksigWyatt** [comment]
Ah, that must be why I'm getting so many warnings. Either one of the solutions above will fix the error. I'm still getting a random error of:

> 'sys/vmmeter.h' file not found 

Under Packages/CLibreSSL-1.0.0/Sources/CLibreSSL/getentropy_osx.c but that's likely due to the fact that it's an `OSX.c` file. And there could be some issues with that.  I'll have to try to see if I can reference my database another way then, perhaps the `REST API`. Thanks for your help. 

Cheers

**Comment by Joannis** [comment]
@ksigWyatt are you writing an app for database administration? If you want to connect your apps to MongoDB directly your server credentials can be read form the app binary itself. Any of your users has the ability to read and connect to your database and get control over it. For this reason, REST APIs are always the best option. If you're writing a database administration app, however, that's a different story.

**Comment by ksigWyatt** [comment]
@Joannis It's for database query - I'm just trying to display and/or update information on the database.
