### ISSUE TITLE
Support for bulk insert and update

### ISSUE THREAD

**Issue by sujaykakkad** [OpenKitten/MongoKitten#94]
Does MongoKitten support bulk insert and update methods as given in the mongodb documentation?

https://docs.mongodb.com/manual/reference/method/Bulk.find.update/#bulk-find-update

**Comment by Joannis** [comment]
Bulk is part of the MongoDB command line tools. But you can programmatically do the same in MongoKitten:

http://mongokitten.openkitten.org/Classes/Collection.html#/s:FC11MongoKitten10Collection6updateFzT8matchingVS_5Query2toV4BSON8Document9upsertingSb8multipleSb12writeConcernGSqOS_12WriteConcern_15stoppingOnErrorGSqSb__Si

http://mongokitten.openkitten.org/Classes/Collection.html#/s:FC11MongoKitten10Collection6insertFzTGSaV4BSON8Document_15stoppingOnErrorGSqSb_12writeConcernGSqOS_12WriteConcern_7timeoutGSqSd__GSaPS1_16ValueConvertible__

**Comment by sujaykakkad** [comment]
In Mongo 3.2 onwards there is db.collection.bulkWrite method. Is there any way to use in mongokitten. 

https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/#db.collection.bulkWrite

**Comment by sujaykakkad** [comment]
Ok so here is what I want to achieve. I have to perform 100,000 updates every week. I will get a csv file which will have 100, 000 records which I have to read and update on mongodb.
eg:
Suppose I have a collection like this
```js
rates = [
  {"name": "ABC", "rate": 10.0},
  {"name": "DEF", "rate": 30.0},
  {"name": "GHI", "rate": 36.5}
]
```
Now I have a csv file like this
```
name rate
ABC  10.5
DEF  29.0
GHI  36.0
```
I will have to update the new rates in the rates collection.
I will have more than 100,000 records in the csv file. I guess this cannot happen in a single mongo query. So I will have to use bulk queries. Is there an other way to achieve this?

**Comment by Joannis** [comment]
You can do this in a single mongo query using MongoKitten using [this implementation](http://mongokitten.openkitten.org/Classes/Collection.html#/s:FC11MongoKitten10Collection6updateFzTGSaT6filterVS_5Query2toV4BSON8Document9upsertingSb8multipleSb__12writeConcernGSqOS_12WriteConcern_15stoppingOnErrorGSqSb__Si)

So let's say you've already converted CSV to a Document looking like the following in JSON:

```json
[
  {"name": "ABC", "rate": 10.0},
  {"name": "DEF", "rate": 30.0},
  {"name": "GHI", "rate": 36.5}
]
```

Or in MongoKitten/Swift syntax:

```swift
let documents: [Document] = [
  ["name": "ABC", "rate": 10.0],
  ["name": "DEF", "rate": 30.0],
  ["name": "GHI", "rate": 36.5]
]
```

We can derive the name/query from this so we'll know what to update and we can read the new rate. And we can use the rate which is in the Document to create an update operation (using $set).

By creating an array of operations like the signature for bulk-updates requires linked above we can pass this set of bulk operations to MongoDB.

```swift
enum MyInternalError : Error {
  case invalidUpdateDocument(Document)
}

let updateOperations: [(filter: Query, to: Document, upserting: Bool, multiple: Bool)]
updateOperations = try documents.map { document in
  guard let name = document["name"] as String?, let rate = document["rate"] as Double? else {
    throw MyInternalError.invalidUpdateDocument(document)
  }

  let updatedDocument: Document = [
    "$set": [
      "rate": rate
    ] as Document
  ]
  
  return (filter: "name" == name, to: updatedDocument, upserting: ???, multiple: false)
}

try collection.update(updateOperations)
```

This will potentially consume quite a bit of memory by doing it in bulk like this since you'll have to load the CSV, convert it to BSON (before this example), then convert BSON to a set of update operations and it'll have to send that to MongoDB. But as a weekly query and on a decent server it shouldn't be a problem for your server.

In the

**Comment by sujaykakkad** [comment]
Well thanks for the solution. It is working similar to bulkWrite method. However to update 100000 documents it takes over 13 seconds which is highly inefficient. Even when I do it with plain javascript it takes over 7 seconds. Is there any efficient way to do this in mongo itself then we can find a way in swift.

**Comment by Joannis** [comment]
I've improved the performance in many points. Could you check this with MongoKitten 4?

**Comment by sujaykakkad** [comment]
Hey Sorry for late reply. I will test this in next week with my API.

**Comment by sujaykakkad** [comment]
```swift
import MongoKitten
import Foundation

let server = try Server("mongodb://localhost")
let database = server["testapp"]

let now = Date()
let cursor = try database["restaurants"].find()
for _ in cursor{
    
}
print(Date().timeIntervalSince(now))
```
I just tested with mongokitten 4 and still it is taking over 20 seconds to parse 25000 records of the 
dataset which I had given
https://docs.mongodb.com/getting-started/shell/import-data/

Can you tell me what I am doing wrong?

My Package.swift looks like this
```swift
// swift-tools-version:3.1

import PackageDescription

let package = Package(
    name: "BasicMongo",
    dependencies: [
        .Package(url: "https://github.com/OpenKitten/MongoKitten.git", "4.0.0-vaportls")
    ]
)
```

**Comment by Joannis** [comment]
I found your problem. I have been running the same code in `0.500207006931305` seconds. When I ran it in debug-mode however the results were much more like yours at `21.6948750019073` seconds.

When you run code in production or an environment where performance matters, always compile on release. `swift build -c release` will do that on the CLI. Your application will not be in `.build/debug/` but in `.build/release/` instead. It literally makes 50x the performance different, and that is in a very optimized application like MongoKitten. In other places you'll find the difference much bigger, still.

For xcode you can change the build configuration from `debug` to release` here:
<img width="960" alt="screen shot 2017-04-27 at 14 33 34" src="https://cloud.githubusercontent.com/assets/1951674/25483542/9a5221c8-2b56-11e7-951e-623eaedd59d0.png">

**Comment by sujaykakkad** [comment]
Thanks for the solution it is now working much faster. So there is a significant difference in performance in release and debug mode.
