### ISSUE TITLE
Add BlueSSL PEMCertificate support to lgaches fork

### ISSUE THREAD

**Issue by tfrank64** [OpenKitten/MongoKitten#96]
Currently, I just need the ability to use this init `init(withPEMCertificateString certificateString: String, usingSelfSignedCerts selfSigned: Bool = true, cipherSuite: String? = nil)`

I have begun the process on my fork here: https://github.com/tfrank64/MongoKitten/commit/e2604fb2813ef89275540e0e2677718f5ae952bc

There is currently an issue in BlueSSL that is causing that app to hang [here](https://github.com/IBM-Swift/BlueSSLService/blob/master/Sources/SSLService.swift#L529). I am working with Bill Abt on that.

**Comment by lgaches** [comment]
Do you need this option to allow client certificate ? Like that :
`mongo --ssl --host hostname.example.com --sslPEMKeyFile /etc/ssl/client.pem --sslCAFile /etc/ssl/ca.pem`

**Comment by tfrank64** [comment]
I don't think so. Part of my problem is that in using the Compose for MongoDB service on Bluemix, SSL is enabled and I don't think you can change it. So I'm given a base64 PEM certificate and thats it.

**Comment by lgaches** [comment]
Ok it's the `sslCAFile` argument.

**Comment by tfrank64** [comment]
@lgaches So here is my issue right now and I'm not so sure that BlueSSL is causing it.

Using [my older MongoKitten code](https://github.com/tfrank64/MongoKitten/releases/tag/3.0.8) that is like 180 commits behind mongokitten31, I can deploy to Bluemix and connect to MongoDB through SSL. It also won't work on my local Linux VM.

Using [newer MongoKitten code from the lgaches fork](https://github.com/tfrank64/MongoKitten/releases/tag/3.0.7) and with my certificate changes on top of them, I cannot deploy to Bluemix or connect to MongoDB through SSL. It also won't work on my local Linux VM.

Both of these use the same version of BlueSSL so its making me wonder whats the real issue.
I'm still troubleshooting, but if you have any ideas let me know. Also, I could give you credentials for my Bluemix mongo instance if you wanted to test with that.

**Comment by Joannis** [comment]
@tfrank64 I'd be up for trying it myself

**Comment by lgaches** [comment]
@tfrank64 using `SSLService.Configuration(withCipherSuite: nil)`,  adding and trusting the CA Certificate to my keychain on MacOS  I passed the SSL Handshake. But the process still hang like you  [here](https://github.com/IBM-Swift/BlueSSLService/blob/master/Sources/SSLService.swift#L529). I'm suspecting MongoKitten here. I have a test instance on Compose so for the moment no needs for your credentials. @Joannis I share you my credentials.

**Comment by tfrank64** [comment]
The [latest changes](https://github.com/lgaches/MongoKitten/commit/8169814034c3002016a9642a0bf72835e9abed77) seem to be working well for me. Let me know when everything is tested and ready to go on the lgaches fork.

**Comment by lgaches** [comment]
Fork with BlueSocket and BlueSSLService is ready. Try https://github.com/lgaches/MongoKitten/releases/tag/3.1.6 .

**Comment by tfrank64** [comment]
The SSL stuff works now, but I'm having some crashes that may be unrelated. That issue is here https://github.com/OpenKitten/MongoKitten/issues/98

**Comment by Joannis** [comment]
Should be fixed now
