### ISSUE TITLE
Mongo not getting connected to remote server

### ISSUE THREAD

**Issue by sujaykakkad** [OpenKitten/MongoKitten#99]
```swift
import MongoKitten
do{
    let server = try Server(hostname: "204.123.14.56", maxConnectionsPerServer: 20)
}catch{
    print(error)
}
```

It throws an error as ```invalidBuildInfoDocument```
It gets connected if I use localhost

**Comment by Joannis** [comment]
I've updated MongoKitten to 3.1.5 to give more information on *why* it's failing. Could you update the MongoKitten dependency to 3.1.5 and return the error thrown?

**Comment by Joannis** [comment]
Did you fix the issue?

**Comment by sujaykakkad** [comment]
No.
It is throwing same error
```missingBuildInfoField("version")```

**Comment by sujaykakkad** [comment]
I upgraded to MongoKitten 3.1.5

**Comment by Joannis** [comment]
What MongoDB version are you running? is it a development build like a Release Candidate, beta, alpha or nightly build? I can understand it failing, then.

**Comment by Joannis** [comment]
I possibly fixed your problem in 3.1.6. Do you mind testing this?

**Comment by sujaykakkad** [comment]
Yes it is working now.

**Comment by sujaykakkad** [comment]
MongoKitten version was 3.2.1
